// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _SQUARELINE_PROJECT_UI_H
#define _SQUARELINE_PROJECT_UI_H

#ifdef __cplusplus
extern "C" {
#endif

#include "lvgl.h"

#include "ui_helpers.h"
#include "ui_comp.h"
#include "ui_comp_hook.h"
#include "ui_events.h"
#include "mtb_disp_dsi_waveshare_4p3.h"

///////////////////// SCREENS ////////////////////

#include "ui_DigitalScreen.h"
#include "ui_AnalogScreen.h"
#include "ui_WeatherScreen1.h"
#include "ui_WeatherScreen2.h"
#include "ui_HealthScreen.h"
#include "ui_MusicScreen.h"
#include "ui_LPScreen.h"

///////////////////// VARIABLES ////////////////////

extern lv_anim_t * DigitClockTimeDotsAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * AnalogClockSecHandAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * AnalogClockMinHandAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * AnalogClockHourHandAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * WindAnimation_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * HeartBeatAnim_Animation(lv_obj_t * TargetObject, int delay);
extern lv_anim_t * MusicTitleScrollAnim_Animation(lv_obj_t * TargetObject, int delay);

// EVENTS

extern lv_obj_t * ui____initial_actions0;

// IMAGES AND IMAGE SETS
LV_IMG_DECLARE(ui_img_white_dot_watch_face_bg_png);    // assets/white_dot_watch_face_bg.png
LV_IMG_DECLARE(ui_img_flash_png);    // assets/flash.png
LV_IMG_DECLARE(ui_img_weather_sun_cloud_png);    // assets/weather_sun_cloud.png
LV_IMG_DECLARE(ui_img_brightness_png);    // assets/brightness.png
LV_IMG_DECLARE(ui_img_step_png);    // assets/step.png
LV_IMG_DECLARE(ui_img_btn_bg_4_png);    // assets/btn_bg_4.png
LV_IMG_DECLARE(ui_img_btn_bg_3_png);    // assets/btn_bg_3.png
LV_IMG_DECLARE(ui_img_clockwise_sec_png);    // assets/clockwise_sec.png
LV_IMG_DECLARE(ui_img_clockwise_min_png);    // assets/clockwise_min.png
LV_IMG_DECLARE(ui_img_clockwise_hour_png);    // assets/clockwise_hour.png
LV_IMG_DECLARE(ui_img_rain_png);    // assets/rain.png
LV_IMG_DECLARE(ui_img_wind_png);    // assets/wind.png
LV_IMG_DECLARE(ui_img_sun_200_200_png);    // assets/sun_200_200.png
LV_IMG_DECLARE(ui_img_sun_png);    // assets/sun.png
LV_IMG_DECLARE(ui_img_visio_clouds_no_bg_152_192_png);    // assets/visio_clouds_no_bg_152_192.png
LV_IMG_DECLARE(ui_img_house_png);    // assets/house.png
LV_IMG_DECLARE(ui_img_wind_animation_no_bg_150_140_png);    // assets/wind_animation_no_bg_150_140.png
LV_IMG_DECLARE(ui_img_weather_cloud_png);    // assets/weather_cloud.png
LV_IMG_DECLARE(ui_img_weather_sun_png);    // assets/weather_sun.png
LV_IMG_DECLARE(ui_img_weather_cloud_fog_png);    // assets/weather_cloud_fog.png
LV_IMG_DECLARE(ui_img_heart_png);    // assets/heart.png
LV_IMG_DECLARE(ui_img_music_prev_button_50_60_no_bg_png);    // assets/music_prev_button_50_60_no_bg.png
LV_IMG_DECLARE(ui_img_music_pause_button_50_50_no_bg_png);    // assets/music_pause_button_50_50_no_bg.png
LV_IMG_DECLARE(ui_img_music_next_button_50_50_no_bg_png);    // assets/music_next_button_50_50_no_bg.png

// FONTS
LV_FONT_DECLARE(ui_font_H1);
LV_FONT_DECLARE(ui_font_Number_big);
LV_FONT_DECLARE(ui_font_Number_extra);
LV_FONT_DECLARE(ui_font_Subtitle);
LV_FONT_DECLARE(ui_font_Title);
LV_FONT_DECLARE(ui_font_Font1);

// UI INIT
void ui_init(void);
void ui_destroy(void);

/* Brightness state consumed by generated arc callbacks. */
extern volatile uint8_t ui_demo_watch_brightness;

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
