// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_WEATHER2TODAYWEATHERUNITPANE_H
#define _UI_COMP_WEATHER2TODAYWEATHERUNITPANE_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Weather2TodayWeatherUnitPane
#define UI_COMP_WEATHER2TODAYWEATHERUNITPANE_WEATHER2TODAYWEATHERUNITPANE 0
#define UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL 1
#define UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON 2
#define UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3 3
#define _UI_COMP_WEATHER2TODAYWEATHERUNITPANE_NUM 4
lv_obj_t * ui_Weather2TodayWeatherUnitPane_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
