// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT WeekForecastUnit

lv_obj_t * ui_WeekForecastUnit_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_WeekForecastUnit;
    cui_WeekForecastUnit = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_WeekForecastUnit, 251);
    lv_obj_set_height(cui_WeekForecastUnit, 50);
    lv_obj_set_x(cui_WeekForecastUnit, -101);
    lv_obj_set_y(cui_WeekForecastUnit, 25);
    lv_obj_set_align(cui_WeekForecastUnit, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_WeekForecastUnit, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_WeekForecastUnit, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cui_WeekForecastUnit, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(cui_WeekForecastUnit, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_left(cui_WeekForecastUnit, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_right(cui_WeekForecastUnit, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_top(cui_WeekForecastUnit, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_bottom(cui_WeekForecastUnit, 0, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_t * cui_WeekWeatherIcon;
    cui_WeekWeatherIcon = lv_image_create(cui_WeekForecastUnit);
    lv_image_set_src(cui_WeekWeatherIcon, &ui_img_weather_cloud_fog_png);
    lv_obj_set_width(cui_WeekWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_WeekWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_WeekWeatherIcon, 94);
    lv_obj_set_y(cui_WeekWeatherIcon, 0);
    lv_obj_set_align(cui_WeekWeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_WeekWeatherIcon, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_WeekWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_DayLabel;
    cui_DayLabel = lv_label_create(cui_WeekForecastUnit);
    lv_obj_set_height(cui_DayLabel, 32);
    lv_obj_set_width(cui_DayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_x(cui_DayLabel, -99);
    lv_obj_set_y(cui_DayLabel, 3);
    lv_obj_set_align(cui_DayLabel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_DayLabel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(cui_DayLabel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_START);
    lv_label_set_text(cui_DayLabel, "Tue");
    lv_obj_set_style_text_color(cui_DayLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_DayLabel, (lv_opa_t)255, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_align(cui_DayLabel, LV_TEXT_ALIGN_CENTER, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_DayLabel, &lv_font_montserrat_20, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);

    lv_obj_t * cui_TempMaxLabel;
    cui_TempMaxLabel = lv_label_create(cui_WeekForecastUnit);
    lv_obj_set_width(cui_TempMaxLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TempMaxLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_TempMaxLabel, -31);
    lv_obj_set_y(cui_TempMaxLabel, 0);
    lv_obj_set_align(cui_TempMaxLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_TempMaxLabel, "24°");
    lv_obj_set_style_text_color(cui_TempMaxLabel, lv_color_hex(0xFFFFFF), LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_TempMaxLabel, (lv_opa_t)255, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_TempMaxLabel, &lv_font_montserrat_20, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);

    lv_obj_t * cui_MinTempLabel;
    cui_MinTempLabel = lv_label_create(cui_WeekForecastUnit);
    lv_obj_set_width(cui_MinTempLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_MinTempLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_MinTempLabel, 39);
    lv_obj_set_y(cui_MinTempLabel, -1);
    lv_obj_set_align(cui_MinTempLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_MinTempLabel, "17°");
    lv_obj_set_style_text_color(cui_MinTempLabel, lv_color_hex(0x808080), LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_MinTempLabel, (lv_opa_t)255, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_MinTempLabel, &lv_font_montserrat_20, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_WEEKFORECASTUNIT_NUM);
    children[UI_COMP_WEEKFORECASTUNIT_WEEKFORECASTUNIT] = cui_WeekForecastUnit;
    children[UI_COMP_WEEKFORECASTUNIT_WEEKWEATHERICON] = cui_WeekWeatherIcon;
    children[UI_COMP_WEEKFORECASTUNIT_DAYLABEL] = cui_DayLabel;
    children[UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL] = cui_TempMaxLabel;
    children[UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL] = cui_MinTempLabel;
    lv_obj_add_event_cb(cui_WeekForecastUnit, get_component_child_event_cb, (lv_event_code_t)LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_WeekForecastUnit, del_component_child_event_cb, (lv_event_code_t)LV_EVENT_DELETE, children);
    ui_comp_WeekForecastUnit_create_hook(cui_WeekForecastUnit);
    return cui_WeekForecastUnit;
}

