// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_embed_port.h"

lv_obj_t * ui_DigitalScreen = NULL;
lv_obj_t * ui_DigiScreenBatteryPanel = NULL;
lv_obj_t * ui_DigiScreenBatteryLevel = NULL;
lv_obj_t * ui_DigiScreenBatteryImg = NULL;
lv_obj_t * ui_DigiScreenDatePanel = NULL;
lv_obj_t * ui_DigiScreenDateLabel = NULL;
lv_obj_t * ui_DigiScreenMonthLabel = NULL;
lv_obj_t * ui_DigiScreenYearLabel = NULL;
lv_obj_t * ui_DigiScreenDayLabel = NULL;
lv_obj_t * ui_DigiScreenTimePanel = NULL;
lv_obj_t * ui_DigiScreenHourLabel = NULL;
lv_obj_t * ui_DigiScreenClockDots = NULL;
lv_obj_t * ui_DigiScreenMinLabel = NULL;
lv_obj_t * ui_DigiScreenWeatherPanel = NULL;
lv_obj_t * ui_WeatherIcon = NULL;
lv_obj_t * ui_WeatherLabel = NULL;
lv_obj_t * ui_DigiScreenBrightnessArc = NULL;
lv_obj_t * ui_DigiScreenBrightnessPercentLabel = NULL;
lv_obj_t * ui_BrightnessIcon = NULL;
lv_obj_t * ui_DigiScreenStepsPanel = NULL;
lv_obj_t * ui_DigiScreenStepsCountLabel = NULL;
lv_obj_t * ui_DigitalScreenStepImg = NULL;
lv_obj_t * ui_WeatherButton = NULL;
// event funtions
void ui_event_DigitalScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(!ui_embed_port_is_enabled() && event_code == LV_EVENT_SCREEN_LOADED) {
        DigitClockTimeDotsAnim_Animation(ui_DigiScreenClockDots, 0);
    }
    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_AnalogScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AnalogScreen_screen_init);
    }
    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_AnalogScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_AnalogScreen_screen_init);
    }
    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_HealthScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HealthScreen_screen_init);
    }
}

void ui_event_DigiScreenBrightnessArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED)
    {
        _ui_arc_set_text_value(ui_DigiScreenBrightnessPercentLabel, target, "", "%");
        ui_demo_watch_brightness = (uint8_t)lv_arc_get_value(target);
    }
}

void ui_event_WeatherButton_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_WeatherScreen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WeatherScreen1_screen_init);
    }
}

// build funtions

void ui_DigitalScreen_screen_init(void)
{
    ui_DigitalScreen = ui_embed_port_create_root();
    lv_obj_remove_flag(ui_DigitalScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_DigitalScreen, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigitalScreen, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_DigitalScreen, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_right(ui_DigitalScreen, 15, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_top(ui_DigitalScreen, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_bottom(ui_DigitalScreen, 0, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenBatteryPanel = lv_obj_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenBatteryPanel, 100);
    lv_obj_set_height(ui_DigiScreenBatteryPanel, 26);
    lv_obj_set_x(ui_DigiScreenBatteryPanel, 1);
    lv_obj_set_y(ui_DigiScreenBatteryPanel, -199);
    lv_obj_set_align(ui_DigiScreenBatteryPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DigiScreenBatteryPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DigiScreenBatteryPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_DigiScreenBatteryPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigiScreenBatteryPanel,(lv_opa_t) 125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_DigiScreenBatteryPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_DigiScreenBatteryPanel, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_DigiScreenBatteryPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenBatteryLevel = lv_label_create(ui_DigiScreenBatteryPanel);
    lv_obj_set_width(ui_DigiScreenBatteryLevel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenBatteryLevel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_DigiScreenBatteryLevel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenBatteryLevel, "86%");
    lv_obj_set_style_text_color(ui_DigiScreenBatteryLevel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenBatteryLevel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenBatteryLevel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenBatteryImg = lv_image_create(ui_DigiScreenBatteryPanel);
    lv_image_set_src(ui_DigiScreenBatteryImg, &ui_img_flash_png);
    lv_obj_set_width(ui_DigiScreenBatteryImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenBatteryImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenBatteryImg, -36);
    lv_obj_set_y(ui_DigiScreenBatteryImg, 0);
    lv_obj_set_align(ui_DigiScreenBatteryImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DigiScreenBatteryImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_DigiScreenBatteryImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DigiScreenDatePanel = lv_obj_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenDatePanel, 160);
    lv_obj_set_height(ui_DigiScreenDatePanel, 80);
    lv_obj_set_x(ui_DigiScreenDatePanel, 6);
    lv_obj_set_y(ui_DigiScreenDatePanel, -127);
    lv_obj_set_align(ui_DigiScreenDatePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DigiScreenDatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DigiScreenDatePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_DigiScreenDatePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigiScreenDatePanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_DigiScreenDatePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_DigiScreenDatePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenDateLabel = lv_label_create(ui_DigiScreenDatePanel);
    lv_obj_set_width(ui_DigiScreenDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenDateLabel, -58);
    lv_obj_set_y(ui_DigiScreenDateLabel, -11);
    lv_obj_set_align(ui_DigiScreenDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenDateLabel, "01");
    lv_obj_set_style_text_color(ui_DigiScreenDateLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenDateLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenDateLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenMonthLabel = lv_label_create(ui_DigiScreenDatePanel);
    lv_obj_set_width(ui_DigiScreenMonthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenMonthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenMonthLabel, -11);
    lv_obj_set_y(ui_DigiScreenMonthLabel, -11);
    lv_obj_set_align(ui_DigiScreenMonthLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenMonthLabel, "JAN");
    lv_obj_set_style_text_color(ui_DigiScreenMonthLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenMonthLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenMonthLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenYearLabel = lv_label_create(ui_DigiScreenDatePanel);
    lv_obj_set_width(ui_DigiScreenYearLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenYearLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenYearLabel, 46);
    lv_obj_set_y(ui_DigiScreenYearLabel, -11);
    lv_obj_set_align(ui_DigiScreenYearLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenYearLabel, "2025");
    lv_obj_set_style_text_color(ui_DigiScreenYearLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenYearLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenYearLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenDayLabel = lv_label_create(ui_DigiScreenDatePanel);
    lv_obj_set_width(ui_DigiScreenDayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenDayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenDayLabel, -9);
    lv_obj_set_y(ui_DigiScreenDayLabel, 19);
    lv_obj_set_align(ui_DigiScreenDayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenDayLabel, "WED");
    lv_obj_set_style_text_color(ui_DigiScreenDayLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenDayLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenDayLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenTimePanel = lv_obj_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenTimePanel, 350);
    lv_obj_set_height(ui_DigiScreenTimePanel, 90);
    lv_obj_set_x(ui_DigiScreenTimePanel, 3);
    lv_obj_set_y(ui_DigiScreenTimePanel, -14);
    lv_obj_set_align(ui_DigiScreenTimePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DigiScreenTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DigiScreenTimePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_DigiScreenTimePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigiScreenTimePanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_DigiScreenTimePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenHourLabel = lv_label_create(ui_DigiScreenTimePanel);
    lv_obj_set_width(ui_DigiScreenHourLabel, 150);
    lv_obj_set_height(ui_DigiScreenHourLabel, 90);
    lv_obj_set_x(ui_DigiScreenHourLabel, -11);
    lv_obj_set_y(ui_DigiScreenHourLabel, 7);
    lv_obj_set_align(ui_DigiScreenHourLabel, LV_ALIGN_LEFT_MID);
    lv_obj_set_style_text_align(ui_DigiScreenHourLabel, LV_TEXT_ALIGN_RIGHT, 0);
    lv_label_set_text(ui_DigiScreenHourLabel, "00");
    lv_obj_set_style_text_color(ui_DigiScreenHourLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenHourLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenHourLabel, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenClockDots = lv_label_create(ui_DigiScreenTimePanel);
    lv_obj_set_width(ui_DigiScreenClockDots, 23);
    lv_obj_set_height(ui_DigiScreenClockDots, 109);
    lv_obj_set_x(ui_DigiScreenClockDots, -1);
    lv_obj_set_y(ui_DigiScreenClockDots, 7);
    lv_obj_set_align(ui_DigiScreenClockDots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenClockDots, ":");
    lv_obj_set_style_text_color(ui_DigiScreenClockDots, lv_color_hex(0xB1ADAD), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenClockDots, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenClockDots, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenMinLabel = lv_label_create(ui_DigiScreenTimePanel);
    lv_obj_set_width(ui_DigiScreenMinLabel, 150);
    lv_obj_set_height(ui_DigiScreenMinLabel, 90);
    lv_obj_set_x(ui_DigiScreenMinLabel, 17);
    lv_obj_set_y(ui_DigiScreenMinLabel, 7);
    lv_obj_set_align(ui_DigiScreenMinLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_DigiScreenMinLabel, "00");
    lv_obj_set_style_text_color(ui_DigiScreenMinLabel, lv_color_hex(0xEE1E1E), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenMinLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenMinLabel, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenWeatherPanel = lv_obj_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenWeatherPanel, 73);
    lv_obj_set_height(ui_DigiScreenWeatherPanel, 68);
    lv_obj_set_x(ui_DigiScreenWeatherPanel, -132);
    lv_obj_set_y(ui_DigiScreenWeatherPanel, -108);
    lv_obj_set_align(ui_DigiScreenWeatherPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DigiScreenWeatherPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DigiScreenWeatherPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_DigiScreenWeatherPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigiScreenWeatherPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_DigiScreenWeatherPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherIcon = lv_image_create(ui_DigiScreenWeatherPanel);
    lv_image_set_src(ui_WeatherIcon, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(ui_WeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherIcon, -10);
    lv_obj_set_y(ui_WeatherIcon, 16);
    lv_obj_set_align(ui_WeatherIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherIcon, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_WeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherLabel = lv_label_create(ui_DigiScreenWeatherPanel);
    lv_obj_set_width(ui_WeatherLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherLabel, -6);
    lv_obj_set_y(ui_WeatherLabel, -17);
    lv_obj_set_align(ui_WeatherLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherLabel, "25°");
    lv_obj_set_style_text_color(ui_WeatherLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_WeatherLabel, (lv_opa_t)255,(lv_style_selector_t) (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_WeatherLabel, &ui_font_H1, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenBrightnessArc = lv_arc_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenBrightnessArc, 380);
    lv_obj_set_height(ui_DigiScreenBrightnessArc, 372);
    lv_obj_set_x(ui_DigiScreenBrightnessArc, -17);
    lv_obj_set_y(ui_DigiScreenBrightnessArc, 26);
    lv_obj_set_align(ui_DigiScreenBrightnessArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_DigiScreenBrightnessArc, 100);
    lv_arc_set_bg_angles(ui_DigiScreenBrightnessArc, 10, 80);
    lv_arc_set_rotation(ui_DigiScreenBrightnessArc, 100);
    lv_obj_set_style_bg_color(ui_DigiScreenBrightnessArc, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigiScreenBrightnessArc, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_color(ui_DigiScreenBrightnessArc, lv_color_hex(0x303030), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_opa(ui_DigiScreenBrightnessArc, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_width(ui_DigiScreenBrightnessArc, 7, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_rounded(ui_DigiScreenBrightnessArc, true, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_set_style_arc_color(ui_DigiScreenBrightnessArc, lv_color_hex(0xB0E14A), LV_PART_INDICATOR);
    lv_obj_set_style_arc_opa(ui_DigiScreenBrightnessArc, 255, LV_PART_INDICATOR);
    lv_obj_set_style_arc_width(ui_DigiScreenBrightnessArc, 7, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(ui_DigiScreenBrightnessArc, true, LV_PART_INDICATOR);

    lv_obj_set_style_bg_color(ui_DigiScreenBrightnessArc, lv_color_hex(0xB0E14A), LV_PART_KNOB);
    lv_obj_set_style_bg_opa(ui_DigiScreenBrightnessArc, (lv_opa_t)255, LV_PART_KNOB);

    ui_DigiScreenBrightnessPercentLabel = lv_label_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenBrightnessPercentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenBrightnessPercentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenBrightnessPercentLabel, -193);
    lv_obj_set_y(ui_DigiScreenBrightnessPercentLabel, -3);
    lv_obj_set_align(ui_DigiScreenBrightnessPercentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenBrightnessPercentLabel, "100%");
    lv_obj_set_style_text_color(ui_DigiScreenBrightnessPercentLabel, lv_color_hex(0xEE1E1E),
                                (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenBrightnessPercentLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenBrightnessPercentLabel, &ui_font_Subtitle,
                               (lv_style_selector_t)LV_PART_MAIN);

    ui_BrightnessIcon = lv_image_create(ui_DigitalScreen);
    lv_image_set_src(ui_BrightnessIcon, &ui_img_brightness_png);
    lv_obj_set_width(ui_BrightnessIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BrightnessIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BrightnessIcon, -45);
    lv_obj_set_y(ui_BrightnessIcon, 171);
    lv_obj_set_align(ui_BrightnessIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_BrightnessIcon, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_BrightnessIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_DigiScreenStepsPanel = lv_obj_create(ui_DigitalScreen);
    lv_obj_set_width(ui_DigiScreenStepsPanel, 100);
    lv_obj_set_height(ui_DigiScreenStepsPanel, 26);
    lv_obj_set_x(ui_DigiScreenStepsPanel, -2);
    lv_obj_set_y(ui_DigiScreenStepsPanel, 168);
    lv_obj_set_align(ui_DigiScreenStepsPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_DigiScreenStepsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_DigiScreenStepsPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_DigiScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_DigiScreenStepsPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_DigiScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_DigiScreenStepsPanel, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_DigiScreenStepsPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigiScreenStepsCountLabel = lv_label_create(ui_DigiScreenStepsPanel);
    lv_obj_set_width(ui_DigiScreenStepsCountLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigiScreenStepsCountLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigiScreenStepsCountLabel, 2);
    lv_obj_set_y(ui_DigiScreenStepsCountLabel, 0);
    lv_obj_set_align(ui_DigiScreenStepsCountLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_DigiScreenStepsCountLabel, "0");
    lv_obj_set_style_text_color(ui_DigiScreenStepsCountLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_DigiScreenStepsCountLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_DigiScreenStepsCountLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_DigitalScreenStepImg = lv_image_create(ui_DigiScreenStepsPanel);
    lv_image_set_src(ui_DigitalScreenStepImg, &ui_img_step_png);
    lv_obj_set_width(ui_DigitalScreenStepImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_DigitalScreenStepImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_DigitalScreenStepImg, -33);
    lv_obj_set_y(ui_DigitalScreenStepImg, 1);
    lv_obj_set_align(ui_DigitalScreenStepImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_DigitalScreenStepImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_DigitalScreenStepImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WeatherButton = ui_Button_create(ui_DigitalScreen);
    lv_obj_set_width(ui_WeatherButton, 60);
    lv_obj_set_height(ui_WeatherButton, 68);
    lv_obj_set_x(ui_WeatherButton, 159);
    lv_obj_set_y(ui_WeatherButton, 99);
    lv_obj_set_style_bg_color(ui_WeatherButton, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherButton, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    lv_image_set_src(ui_comp_get_child(ui_WeatherButton, UI_COMP_BUTTON_BTNICON), &ui_img_weather_sun_cloud_png);
    lv_obj_set_x(ui_comp_get_child(ui_WeatherButton, UI_COMP_BUTTON_BTNICON), -10);
    lv_obj_set_y(ui_comp_get_child(ui_WeatherButton, UI_COMP_BUTTON_BTNICON), -9);

    lv_image_set_src(ui_comp_get_child(ui_WeatherButton, UI_COMP_BUTTON_BTNBAR), &ui_img_btn_bg_3_png);
    lv_obj_set_x(ui_comp_get_child(ui_WeatherButton, UI_COMP_BUTTON_BTNBAR), 11);
    lv_obj_set_y(ui_comp_get_child(ui_WeatherButton, UI_COMP_BUTTON_BTNBAR), 10);

    lv_obj_add_event_cb(ui_DigiScreenBrightnessArc, ui_event_DigiScreenBrightnessArc, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WeatherButton, ui_event_WeatherButton_Button, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_DigitalScreen, ui_event_DigitalScreen, (lv_event_code_t)LV_EVENT_ALL, NULL);

}

void ui_DigitalScreen_screen_destroy(void)
{
    if(ui_DigitalScreen) lv_obj_del(ui_DigitalScreen);

    // NULL screen variables
    ui_DigitalScreen = NULL;
    ui_DigiScreenBatteryPanel = NULL;
    ui_DigiScreenBatteryLevel = NULL;
    ui_DigiScreenBatteryImg = NULL;
    ui_DigiScreenDatePanel = NULL;
    ui_DigiScreenDateLabel = NULL;
    ui_DigiScreenMonthLabel = NULL;
    ui_DigiScreenYearLabel = NULL;
    ui_DigiScreenDayLabel = NULL;
    ui_DigiScreenTimePanel = NULL;
    ui_DigiScreenHourLabel = NULL;
    ui_DigiScreenClockDots = NULL;
    ui_DigiScreenMinLabel = NULL;
    ui_DigiScreenWeatherPanel = NULL;
    ui_WeatherIcon = NULL;
    ui_WeatherLabel = NULL;
    ui_DigiScreenBrightnessArc = NULL;
    ui_DigiScreenBrightnessPercentLabel = NULL;
    ui_BrightnessIcon = NULL;
    ui_DigiScreenStepsPanel = NULL;
    ui_DigiScreenStepsCountLabel = NULL;
    ui_DigitalScreenStepImg = NULL;
    ui_WeatherButton = NULL;

}
