// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_embed_port.h"

lv_obj_t * ui_HealthScreen = NULL;
lv_obj_t * ui_Label1 = NULL;
lv_obj_t * ui_BloodPressureSYSPanel = NULL;
lv_obj_t * ui_BloodPressureSYSLabel = NULL;
lv_obj_t * ui_BloodPressureUnitLabel = NULL;
lv_obj_t * ui_BloodPressureDIAPanel = NULL;
lv_obj_t * ui_BloodPressureDIALabel = NULL;
lv_obj_t * ui_BloodPressureDIAUnitLabel = NULL;
lv_obj_t * ui_BloodPressureSYSValueLabel = NULL;
lv_obj_t * ui_BloodPressureDIAValueLabel = NULL;
lv_obj_t * ui_HeartAnimPanel = NULL;
lv_obj_t * ui_HeartImgContainPanel = NULL;
lv_obj_t * ui_HeartImg = NULL;
lv_obj_t * ui_HeartBeatAnimSpinner = NULL;
lv_obj_t * ui_HeartRateLabel = NULL;
lv_obj_t * ui_HeartBeatValueLabel = NULL;
lv_obj_t * ui_HeartIcon = NULL;
lv_obj_t * ui_HeartBeatUnitLabel = NULL;
lv_obj_t * ui_HealthScrnHomeBtn = NULL;
// event funtions
void ui_event_HealthScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(!ui_embed_port_is_enabled() && event_code == LV_EVENT_SCREEN_LOADED) {
        HeartBeatAnim_Animation(ui_HeartImg, 0);
    }
    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_TOP) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_MusicScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_MusicScreen_screen_init);
    }
    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
}

void ui_event_HealthScrnHomeBtn_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
}

// build funtions

void ui_HealthScreen_screen_init(void)
{
    ui_HealthScreen = ui_embed_port_create_root();
    lv_obj_remove_flag(ui_HealthScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HealthScreen, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_HealthScreen, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);

    ui_Label1 = lv_label_create(ui_HealthScreen);
    lv_obj_set_width(ui_Label1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_Label1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_Label1, -102);
    lv_obj_set_y(ui_Label1, -95);
    lv_obj_set_align(ui_Label1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_Label1, "Blood Pressure");
    lv_obj_set_style_text_color(ui_Label1, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_Label1, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_Label1, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_Label1, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Label1, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureSYSPanel = lv_obj_create(ui_HealthScreen);
    lv_obj_set_width(ui_BloodPressureSYSPanel, 143);
    lv_obj_set_height(ui_BloodPressureSYSPanel, 50);
    lv_obj_set_x(ui_BloodPressureSYSPanel, -108);
    lv_obj_set_y(ui_BloodPressureSYSPanel, -57);
    lv_obj_set_align(ui_BloodPressureSYSPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BloodPressureSYSPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_BloodPressureSYSPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_BloodPressureSYSPanel,(lv_opa_t) 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_BloodPressureSYSPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureSYSLabel = lv_label_create(ui_BloodPressureSYSPanel);
    lv_obj_set_width(ui_BloodPressureSYSLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BloodPressureSYSLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BloodPressureSYSLabel, -39);
    lv_obj_set_y(ui_BloodPressureSYSLabel, 0);
    lv_obj_set_align(ui_BloodPressureSYSLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BloodPressureSYSLabel, "SYS");
    lv_obj_set_style_text_color(ui_BloodPressureSYSLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_BloodPressureSYSLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_BloodPressureSYSLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureUnitLabel = lv_label_create(ui_BloodPressureSYSPanel);
    lv_obj_set_width(ui_BloodPressureUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BloodPressureUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BloodPressureUnitLabel, 36);
    lv_obj_set_y(ui_BloodPressureUnitLabel, 4);
    lv_obj_set_align(ui_BloodPressureUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BloodPressureUnitLabel, "mmhg");
    lv_obj_set_style_text_color(ui_BloodPressureUnitLabel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_BloodPressureUnitLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_BloodPressureUnitLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureDIAPanel = lv_obj_create(ui_HealthScreen);
    lv_obj_set_width(ui_BloodPressureDIAPanel, 143);
    lv_obj_set_height(ui_BloodPressureDIAPanel, 50);
    lv_obj_set_x(ui_BloodPressureDIAPanel, -109);
    lv_obj_set_y(ui_BloodPressureDIAPanel, 54);
    lv_obj_set_align(ui_BloodPressureDIAPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_BloodPressureDIAPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_BloodPressureDIAPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_BloodPressureDIAPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_BloodPressureDIAPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_BloodPressureDIAPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureDIALabel = lv_label_create(ui_BloodPressureDIAPanel);
    lv_obj_set_width(ui_BloodPressureDIALabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BloodPressureDIALabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BloodPressureDIALabel, -39);
    lv_obj_set_y(ui_BloodPressureDIALabel, 0);
    lv_obj_set_align(ui_BloodPressureDIALabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BloodPressureDIALabel, "DIA");
    lv_obj_set_style_text_color(ui_BloodPressureDIALabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_BloodPressureDIALabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_BloodPressureDIALabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureDIAUnitLabel = lv_label_create(ui_BloodPressureDIAPanel);
    lv_obj_set_width(ui_BloodPressureDIAUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BloodPressureDIAUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BloodPressureDIAUnitLabel, 36);
    lv_obj_set_y(ui_BloodPressureDIAUnitLabel, 4);
    lv_obj_set_align(ui_BloodPressureDIAUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BloodPressureDIAUnitLabel, "mmhg");
    lv_obj_set_style_text_color(ui_BloodPressureDIAUnitLabel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_BloodPressureDIAUnitLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_BloodPressureDIAUnitLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureSYSValueLabel = lv_label_create(ui_HealthScreen);
    lv_obj_set_width(ui_BloodPressureSYSValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BloodPressureSYSValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BloodPressureSYSValueLabel, -145);
    lv_obj_set_y(ui_BloodPressureSYSValueLabel, -8);
    lv_obj_set_align(ui_BloodPressureSYSValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BloodPressureSYSValueLabel, "-");
    lv_obj_set_style_text_color(ui_BloodPressureSYSValueLabel, lv_color_hex(0xEA1111), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_BloodPressureSYSValueLabel, (lv_opa_t)255, (lv_style_selector_t)(lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_BloodPressureSYSValueLabel, &lv_font_montserrat_40, (lv_style_selector_t)LV_PART_MAIN);

    ui_BloodPressureDIAValueLabel = lv_label_create(ui_HealthScreen);
    lv_obj_set_width(ui_BloodPressureDIAValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_BloodPressureDIAValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_BloodPressureDIAValueLabel, -146);
    lv_obj_set_y(ui_BloodPressureDIAValueLabel, 101);
    lv_obj_set_align(ui_BloodPressureDIAValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_BloodPressureDIAValueLabel, "-");
    lv_obj_set_style_text_color(ui_BloodPressureDIAValueLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_BloodPressureDIAValueLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_BloodPressureDIAValueLabel, &lv_font_montserrat_40, (lv_style_selector_t)LV_PART_MAIN);

    ui_HeartAnimPanel = lv_obj_create(ui_HealthScreen);
    lv_obj_set_width(ui_HeartAnimPanel, 239);
    lv_obj_set_height(ui_HeartAnimPanel, 236);
    lv_obj_set_x(ui_HeartAnimPanel, 85);
    lv_obj_set_y(ui_HeartAnimPanel, -63);
    lv_obj_set_align(ui_HeartAnimPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeartAnimPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_HeartAnimPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_HeartAnimPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_HeartAnimPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_HeartImgContainPanel = lv_obj_create(ui_HeartAnimPanel);
    lv_obj_set_width(ui_HeartImgContainPanel, 160);
    lv_obj_set_height(ui_HeartImgContainPanel, 160);
    lv_obj_set_x(ui_HeartImgContainPanel, -2);
    lv_obj_set_y(ui_HeartImgContainPanel, -3);
    lv_obj_set_align(ui_HeartImgContainPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeartImgContainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeartImgContainPanel, 160, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_HeartImgContainPanel, lv_color_hex(0xED2606), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_HeartImgContainPanel,(lv_opa_t) 80, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_HeartImgContainPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_HeartImg = lv_image_create(ui_HeartImgContainPanel);
    lv_image_set_src(ui_HeartImg, &ui_img_heart_png);
    lv_obj_set_width(ui_HeartImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(ui_HeartImg, LV_ALIGN_CENTER);
    lv_image_set_scale(ui_HeartImg, 640);
    lv_obj_add_flag(ui_HeartImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HeartImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeartBeatAnimSpinner = lv_spinner_create(ui_HeartAnimPanel);
    lv_obj_set_width(ui_HeartBeatAnimSpinner, 200);
    lv_obj_set_height(ui_HeartBeatAnimSpinner, 191);
    lv_obj_set_x(ui_HeartBeatAnimSpinner, 3);
    lv_obj_set_y(ui_HeartBeatAnimSpinner, -4);
    lv_obj_set_align(ui_HeartBeatAnimSpinner, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_HeartBeatAnimSpinner, LV_OBJ_FLAG_CLICKABLE);      /// Flags
    lv_obj_set_style_radius(ui_HeartBeatAnimSpinner, 100, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_HeartBeatAnimSpinner, 2, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_HeartBeatAnimSpinner, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_color(ui_HeartBeatAnimSpinner, lv_color_hex(0x3E413E), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_opa(ui_HeartBeatAnimSpinner, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_width(ui_HeartBeatAnimSpinner, 6, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_set_style_arc_color(ui_HeartBeatAnimSpinner, lv_color_hex(0xEE1C18), LV_PART_INDICATOR);
    lv_obj_set_style_arc_opa(ui_HeartBeatAnimSpinner, 255, LV_PART_INDICATOR);
    lv_obj_set_style_arc_width(ui_HeartBeatAnimSpinner, 6, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(ui_HeartBeatAnimSpinner, true, LV_PART_INDICATOR);
    if (ui_embed_port_is_enabled()) {
        /* Keep spinning in embed mode but slow it down to reduce redraw pressure. */
        lv_spinner_set_anim_params(ui_HeartBeatAnimSpinner, 3000, 220);
    }

    ui_HeartRateLabel = lv_label_create(ui_HealthScreen);
    lv_obj_set_width(ui_HeartRateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartRateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartRateLabel, 67);
    lv_obj_set_y(ui_HeartRateLabel, 53);
    lv_obj_set_align(ui_HeartRateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartRateLabel, "Heart Rate");
    lv_obj_set_style_text_color(ui_HeartRateLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_HeartRateLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_HeartRateLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_HeartBeatValueLabel = lv_label_create(ui_HealthScreen);
    lv_obj_set_width(ui_HeartBeatValueLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartBeatValueLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartBeatValueLabel, 30);
    lv_obj_set_y(ui_HeartBeatValueLabel, 90);
    lv_obj_set_align(ui_HeartBeatValueLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartBeatValueLabel, "-");
    lv_obj_set_style_text_color(ui_HeartBeatValueLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_HeartBeatValueLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_HeartBeatValueLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_HeartIcon = lv_image_create(ui_HealthScreen);
    lv_image_set_src(ui_HeartIcon, &ui_img_heart_png);
    lv_obj_set_width(ui_HeartIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartIcon, 78);
    lv_obj_set_y(ui_HeartIcon, 91);
    lv_obj_set_align(ui_HeartIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_HeartIcon, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_HeartIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_HeartBeatUnitLabel = lv_label_create(ui_HealthScreen);
    lv_obj_set_width(ui_HeartBeatUnitLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_HeartBeatUnitLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_HeartBeatUnitLabel, 133);
    lv_obj_set_y(ui_HeartBeatUnitLabel, 89);
    lv_obj_set_align(ui_HeartBeatUnitLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_HeartBeatUnitLabel, "bpm");
    lv_obj_set_style_text_color(ui_HeartBeatUnitLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_HeartBeatUnitLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_HeartBeatUnitLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_HealthScrnHomeBtn = ui_Button_create(ui_HealthScreen);
    lv_obj_set_x(ui_HealthScrnHomeBtn, 121);
    lv_obj_set_y(ui_HealthScrnHomeBtn, 148);

    lv_image_set_src(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNICON), &ui_img_house_png);
    lv_obj_set_x(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNICON), -5);
    lv_obj_set_y(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNICON), -11);

    lv_image_set_src(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNBAR), &ui_img_btn_bg_3_png);
    lv_obj_set_x(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNBAR), 11);
    lv_obj_set_y(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNBAR), 4);
    lv_image_set_rotation(ui_comp_get_child(ui_HealthScrnHomeBtn, UI_COMP_BUTTON_BTNBAR), 80);

    lv_obj_add_event_cb(ui_HealthScrnHomeBtn, ui_event_HealthScrnHomeBtn_Button, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_HealthScreen, ui_event_HealthScreen, (lv_event_code_t)LV_EVENT_ALL, NULL);

}

void ui_HealthScreen_screen_destroy(void)
{
    if(ui_HealthScreen) lv_obj_del(ui_HealthScreen);

    // NULL screen variables
    ui_HealthScreen = NULL;
    ui_Label1 = NULL;
    ui_BloodPressureSYSPanel = NULL;
    ui_BloodPressureSYSLabel = NULL;
    ui_BloodPressureUnitLabel = NULL;
    ui_BloodPressureDIAPanel = NULL;
    ui_BloodPressureDIALabel = NULL;
    ui_BloodPressureDIAUnitLabel = NULL;
    ui_BloodPressureSYSValueLabel = NULL;
    ui_BloodPressureDIAValueLabel = NULL;
    ui_HeartAnimPanel = NULL;
    ui_HeartImgContainPanel = NULL;
    ui_HeartImg = NULL;
    ui_HeartBeatAnimSpinner = NULL;
    ui_HeartRateLabel = NULL;
    ui_HeartBeatValueLabel = NULL;
    ui_HeartIcon = NULL;
    ui_HeartBeatUnitLabel = NULL;
    ui_HealthScrnHomeBtn = NULL;

}
