// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_LPSCREEN_H
#define UI_LPSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_LPScreen
extern void ui_LPScreen_screen_init(void);
extern void ui_LPScreen_screen_destroy(void);
extern lv_obj_t * ui_LPScreen;
extern lv_obj_t * ui_LPScreenTimePanel;
extern lv_obj_t * ui_LPScreenHourLabel;
extern lv_obj_t * ui_LPScreenClockDots;
extern lv_obj_t * ui_LPScreenMinLabel;
extern lv_obj_t * ui_LPScreenStepsPanel;
extern lv_obj_t * ui_LPScreenStepsLabel;
extern lv_obj_t * ui_LPScreenStepImg;
extern lv_obj_t * ui_LPScreenDatePanel;
extern lv_obj_t * ui_LPScreenDateLabel;
extern lv_obj_t * ui_LPScreenMonthLabel;
extern lv_obj_t * ui_LPScreenDayLabel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

