// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_embed_port.h"

lv_obj_t * ui_LPScreen = NULL;
lv_obj_t * ui_LPScreenTimePanel = NULL;
lv_obj_t * ui_LPScreenHourLabel = NULL;
lv_obj_t * ui_LPScreenClockDots = NULL;
lv_obj_t * ui_LPScreenMinLabel = NULL;
lv_obj_t * ui_LPScreenStepsPanel = NULL;
lv_obj_t * ui_LPScreenStepsLabel = NULL;
lv_obj_t * ui_LPScreenStepImg = NULL;
lv_obj_t * ui_LPScreenDatePanel = NULL;
lv_obj_t * ui_LPScreenDateLabel = NULL;
lv_obj_t * ui_LPScreenMonthLabel = NULL;
lv_obj_t * ui_LPScreenDayLabel = NULL;
// event funtions

// build funtions

void ui_LPScreen_screen_init(void)
{
    ui_LPScreen = ui_embed_port_create_root();
    lv_obj_remove_flag(ui_LPScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LPScreen, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreen, (lv_opa_t)255,(lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_src(ui_LPScreen, &ui_img_white_dot_watch_face_bg_png, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenTimePanel = lv_obj_create(ui_LPScreen);
    lv_obj_set_width(ui_LPScreenTimePanel, 220);
    lv_obj_set_height(ui_LPScreenTimePanel, 60);
    lv_obj_set_x(ui_LPScreenTimePanel, 0);
    lv_obj_set_y(ui_LPScreenTimePanel, -15);
    lv_obj_set_align(ui_LPScreenTimePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LPScreenTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LPScreenTimePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreenTimePanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_LPScreenTimePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenHourLabel = lv_label_create(ui_LPScreenTimePanel);
    lv_obj_set_width(ui_LPScreenHourLabel, 76);
    lv_obj_set_height(ui_LPScreenHourLabel, 60);
    lv_obj_set_x(ui_LPScreenHourLabel, 2);
    lv_obj_set_y(ui_LPScreenHourLabel, 1);
    lv_obj_set_align(ui_LPScreenHourLabel, LV_ALIGN_LEFT_MID);
    lv_label_set_text(ui_LPScreenHourLabel, "12");
    lv_obj_set_style_text_color(ui_LPScreenHourLabel, lv_color_hex(0x6B6B6B), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenHourLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenHourLabel, &lv_font_montserrat_40, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenClockDots = lv_label_create(ui_LPScreenTimePanel);
    lv_obj_set_width(ui_LPScreenClockDots, 14);
    lv_obj_set_height(ui_LPScreenClockDots, 59);
    lv_obj_set_x(ui_LPScreenClockDots, 2);
    lv_obj_set_y(ui_LPScreenClockDots, -2);
    lv_obj_set_align(ui_LPScreenClockDots, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenClockDots, ":");
    lv_obj_set_style_text_color(ui_LPScreenClockDots, lv_color_hex(0xB1ADAD), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenClockDots, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenClockDots, &lv_font_montserrat_40, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenMinLabel = lv_label_create(ui_LPScreenTimePanel);
    lv_obj_set_width(ui_LPScreenMinLabel, 66);
    lv_obj_set_height(ui_LPScreenMinLabel, 60);
    lv_obj_set_x(ui_LPScreenMinLabel, 0);
    lv_obj_set_y(ui_LPScreenMinLabel, 2);
    lv_obj_set_align(ui_LPScreenMinLabel, LV_ALIGN_RIGHT_MID);
    lv_label_set_text(ui_LPScreenMinLabel, "00");
    lv_obj_set_style_text_color(ui_LPScreenMinLabel, lv_color_hex(0xEE1E1E), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenMinLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenMinLabel, &lv_font_montserrat_40, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenStepsPanel = lv_obj_create(ui_LPScreen);
    lv_obj_set_width(ui_LPScreenStepsPanel, 100);
    lv_obj_set_height(ui_LPScreenStepsPanel, 26);
    lv_obj_set_x(ui_LPScreenStepsPanel, -2);
    lv_obj_set_y(ui_LPScreenStepsPanel, 168);
    lv_obj_set_align(ui_LPScreenStepsPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LPScreenStepsPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_LPScreenStepsPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_LPScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreenStepsPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_LPScreenStepsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_LPScreenStepsPanel,255,(lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_LPScreenStepsPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenStepsLabel = lv_label_create(ui_LPScreenStepsPanel);
    lv_obj_set_width(ui_LPScreenStepsLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenStepsLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenStepsLabel, 2);
    lv_obj_set_y(ui_LPScreenStepsLabel, 0);
    lv_obj_set_align(ui_LPScreenStepsLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenStepsLabel, "0");
    lv_obj_set_style_text_color(ui_LPScreenStepsLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenStepsLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenStepsLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenStepImg = lv_image_create(ui_LPScreenStepsPanel);
    lv_image_set_src(ui_LPScreenStepImg, &ui_img_step_png);
    lv_obj_set_width(ui_LPScreenStepImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenStepImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenStepImg, -33);
    lv_obj_set_y(ui_LPScreenStepImg, 1);
    lv_obj_set_align(ui_LPScreenStepImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_LPScreenStepImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_LPScreenStepImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_LPScreenDatePanel = lv_obj_create(ui_LPScreen);
    lv_obj_set_width(ui_LPScreenDatePanel, 160);
    lv_obj_set_height(ui_LPScreenDatePanel, 80);
    lv_obj_set_x(ui_LPScreenDatePanel, 0);
    lv_obj_set_y(ui_LPScreenDatePanel, 84);
    lv_obj_set_align(ui_LPScreenDatePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_LPScreenDatePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_LPScreenDatePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_LPScreenDatePanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_LPScreenDatePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_LPScreenDatePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenDateLabel = lv_label_create(ui_LPScreenDatePanel);
    lv_obj_set_width(ui_LPScreenDateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenDateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenDateLabel, -58);
    lv_obj_set_y(ui_LPScreenDateLabel, -11);
    lv_obj_set_align(ui_LPScreenDateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenDateLabel, "01");
    lv_obj_set_style_text_color(ui_LPScreenDateLabel, lv_color_hex(0xFF0000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenDateLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenDateLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenMonthLabel = lv_label_create(ui_LPScreenDatePanel);
    lv_obj_set_width(ui_LPScreenMonthLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenMonthLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenMonthLabel, -11);
    lv_obj_set_y(ui_LPScreenMonthLabel, -11);
    lv_obj_set_align(ui_LPScreenMonthLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenMonthLabel, "JAN");
    lv_obj_set_style_text_color(ui_LPScreenMonthLabel, lv_color_hex(0xFF0000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenMonthLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenMonthLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_LPScreenDayLabel = lv_label_create(ui_LPScreenDatePanel);
    lv_obj_set_width(ui_LPScreenDayLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_LPScreenDayLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_LPScreenDayLabel, 46);
    lv_obj_set_y(ui_LPScreenDayLabel, -11);
    lv_obj_set_align(ui_LPScreenDayLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_LPScreenDayLabel, "WED");
    lv_obj_set_style_text_color(ui_LPScreenDayLabel, lv_color_hex(0xFF0000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_LPScreenDayLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_LPScreenDayLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

}

void ui_LPScreen_screen_destroy(void)
{
    if(ui_LPScreen) lv_obj_del(ui_LPScreen);

    // NULL screen variables
    ui_LPScreen = NULL;
    ui_LPScreenTimePanel = NULL;
    ui_LPScreenHourLabel = NULL;
    ui_LPScreenClockDots = NULL;
    ui_LPScreenMinLabel = NULL;
    ui_LPScreenStepsPanel = NULL;
    ui_LPScreenStepsLabel = NULL;
    ui_LPScreenStepImg = NULL;
    ui_LPScreenDatePanel = NULL;
    ui_LPScreenDateLabel = NULL;
    ui_LPScreenMonthLabel = NULL;
    ui_LPScreenDayLabel = NULL;

}
