// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_MUSICSCREEN_H
#define UI_MUSICSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_MusicScreen
extern void ui_MusicScreen_screen_init(void);
extern void ui_MusicScreen_screen_destroy(void);
extern void ui_event_MusicScreen(lv_event_t * e);
extern lv_obj_t * ui_MusicScreen;
extern lv_obj_t * ui_MusicTitleLabel;
extern lv_obj_t * ui_MusicPrevButtonPanel;
extern lv_obj_t * ui_MusicPausePlayButtonPanel;
extern lv_obj_t * ui_MusicNextButtonPanel;
extern lv_obj_t * ui_MusicScreenVolumePanel;
extern void ui_event_MusicScreenVolumeArc(lv_event_t * e);
extern lv_obj_t * ui_MusicScreenVolumeArc;
extern lv_obj_t * ui_MusicScreenVolumeNameLabel;
extern lv_obj_t * ui_MusicScreenVolumePercent;
extern lv_obj_t * ui_MusicTimePanel;
extern lv_obj_t * ui_MusicCurrTimeMinPanel;
extern lv_obj_t * ui_MusicCurrTimeDotsPanel;
extern lv_obj_t * ui_MusicCurrTimeSecPanel;
extern lv_obj_t * ui_MusicTimeSlashPanel;
extern lv_obj_t * ui_MusicTotalTimeMinPanel;
extern lv_obj_t * ui_MusicTotalTimeDotsPanel;
extern lv_obj_t * ui_MusicTotalTimeSecPanel;
extern void ui_event_MusicScreenHomeBtnPanel_Button(lv_event_t * e);
extern lv_obj_t * ui_MusicScreenHomeBtnPanel;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

