// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_embed_port.h"

lv_obj_t * ui_WeatherScreen2 = NULL;
lv_obj_t * ui_Weather2CityNamePanel = NULL;
lv_obj_t * ui_weather2CityLabel = NULL;
lv_obj_t * ui_weather2DateLabel = NULL;
lv_obj_t * ui_Weather2TodayWeatherPanel = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane1 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane2 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane3 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane4 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane5 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane6 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane7 = NULL;
lv_obj_t * ui_Weather2TodayWeatherUnitPane8 = NULL;
lv_obj_t * ui_TodayForecastLabel = NULL;
lv_obj_t * ui_WeatherScrn2HomeBtn = NULL;
lv_obj_t * ui_WeatherScrn2WeekForecastPanel = NULL;
lv_obj_t * ui_WeekForecastUnit = NULL;
lv_obj_t * ui_WeekForecastUnit1 = NULL;
lv_obj_t * ui_WeekForecastUnit2 = NULL;
lv_obj_t * ui_WeekForecastUnit3 = NULL;
lv_obj_t * ui_WeekForecastUnit4 = NULL;
lv_obj_t * ui_WeekForecastUnit5 = NULL;
lv_obj_t * ui_WeekForecastLabel = NULL;
lv_obj_t * ui_WeatherScreen2SliderPanel = NULL;
lv_obj_t * ui_SliderDot1 = NULL;
lv_obj_t * ui_SliderDot2 = NULL;
// event funtions
void ui_event_WeatherScreen2(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_RIGHT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_WeatherScreen1, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WeatherScreen1_screen_init);
    }
}

void ui_event_WeatherScrn2HomeBtn_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
}

// build funtions

void ui_WeatherScreen2_screen_init(void)
{
    ui_WeatherScreen2 = ui_embed_port_create_root();
    lv_obj_remove_flag(ui_WeatherScreen2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherScreen2, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen2, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_src(ui_WeatherScreen2, &ui_img_white_dot_watch_face_bg_png, (lv_style_selector_t)LV_PART_MAIN);

    ui_Weather2CityNamePanel = lv_obj_create(ui_WeatherScreen2);
    lv_obj_set_width(ui_Weather2CityNamePanel, 162);
    lv_obj_set_height(ui_Weather2CityNamePanel, 61);
    lv_obj_set_x(ui_Weather2CityNamePanel, -1);
    lv_obj_set_y(ui_Weather2CityNamePanel, -385);
    lv_obj_set_align(ui_Weather2CityNamePanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_Weather2CityNamePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_Weather2CityNamePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Weather2CityNamePanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_Weather2CityNamePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_Weather2CityNamePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_weather2CityLabel = lv_label_create(ui_Weather2CityNamePanel);
    lv_obj_set_width(ui_weather2CityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather2CityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather2CityLabel, -5);
    lv_obj_set_y(ui_weather2CityLabel, -15);
    lv_obj_set_align(ui_weather2CityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather2CityLabel, "Thailand");
    lv_obj_set_style_text_color(ui_weather2CityLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_weather2CityLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_weather2CityLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_weather2DateLabel = lv_label_create(ui_Weather2CityNamePanel);
    lv_obj_set_width(ui_weather2DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather2DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather2DateLabel, -1);
    lv_obj_set_y(ui_weather2DateLabel, 11);
    lv_obj_set_align(ui_weather2DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather2DateLabel, "30. 10. 2026");
    lv_obj_set_style_text_color(ui_weather2DateLabel, lv_color_hex(0x6D6D6D), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_weather2DateLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_weather2DateLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_Weather2TodayWeatherPanel = lv_obj_create(ui_WeatherScreen2);
    lv_obj_set_height(ui_Weather2TodayWeatherPanel, 132);
    lv_obj_set_width(ui_Weather2TodayWeatherPanel, lv_pct(50));
    lv_obj_set_x(ui_Weather2TodayWeatherPanel, 0);
    lv_obj_set_y(ui_Weather2TodayWeatherPanel, -55);
    lv_obj_set_align(ui_Weather2TodayWeatherPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_Weather2TodayWeatherPanel, LV_FLEX_FLOW_ROW);
    lv_obj_set_flex_align(ui_Weather2TodayWeatherPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER);
    lv_obj_set_style_bg_color(ui_Weather2TodayWeatherPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_Weather2TodayWeatherPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_Weather2TodayWeatherPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_left(ui_Weather2TodayWeatherPanel, 6, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_right(ui_Weather2TodayWeatherPanel, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_top(ui_Weather2TodayWeatherPanel, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_bottom(ui_Weather2TodayWeatherPanel, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_row(ui_Weather2TodayWeatherPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_pad_column(ui_Weather2TodayWeatherPanel, 20, (lv_style_selector_t)LV_PART_MAIN);

    ui_Weather2TodayWeatherUnitPane1 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane1, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane1, -10);

    ui_Weather2TodayWeatherUnitPane2 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane2, 83);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane2, -36);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane2, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "16:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane2,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_cloud_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane2, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "26°");

    ui_Weather2TodayWeatherUnitPane3 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane3, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane3, -10);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane3, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "17:00");

    ui_Weather2TodayWeatherUnitPane = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane, -57);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane, -48);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "18:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "22°");

    ui_Weather2TodayWeatherUnitPane4 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane4, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane4, -10);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane4, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "19:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane4,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_cloud_fog_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane4, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "21°");

    ui_Weather2TodayWeatherUnitPane5 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane5, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane5, -10);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane5, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "20:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane5,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane5, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "20°");

    ui_Weather2TodayWeatherUnitPane6 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane6, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane6, -10);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane6, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "21:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane6,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane6, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "22°");

    ui_Weather2TodayWeatherUnitPane7 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane7, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane7, -10);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane7, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "22:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane7,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane7, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "19°");

    ui_Weather2TodayWeatherUnitPane8 = ui_Weather2TodayWeatherUnitPane_create(ui_Weather2TodayWeatherPanel);
    lv_obj_set_x(ui_Weather2TodayWeatherUnitPane8, 103);
    lv_obj_set_y(ui_Weather2TodayWeatherUnitPane8, -10);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane8, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL),
                      "23:00");

    lv_image_set_src(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane8,
                                       UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON), &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_Weather2TodayWeatherUnitPane8, UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3),
                      "17°");

    ui_TodayForecastLabel = lv_label_create(ui_WeatherScreen2);
    lv_obj_set_width(ui_TodayForecastLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_TodayForecastLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_TodayForecastLabel, 0);
    lv_obj_set_y(ui_TodayForecastLabel, -143);
    lv_obj_set_align(ui_TodayForecastLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_TodayForecastLabel, "Today's Forecast");
    lv_obj_set_style_text_color(ui_TodayForecastLabel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_TodayForecastLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_TodayForecastLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScrn2HomeBtn = ui_Button_create(ui_WeatherScreen2);
    lv_obj_set_x(ui_WeatherScrn2HomeBtn, 166);
    lv_obj_set_y(ui_WeatherScrn2HomeBtn, 88);

    lv_image_set_src(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNICON), &ui_img_house_png);
    lv_obj_set_x(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNICON), -2);
    lv_obj_set_y(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNICON), -12);

    lv_image_set_src(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNBAR), &ui_img_btn_bg_3_png);
    lv_obj_set_x(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNBAR), 16);
    lv_obj_set_y(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNBAR), 0);
    lv_image_set_rotation(ui_comp_get_child(ui_WeatherScrn2HomeBtn, UI_COMP_BUTTON_BTNBAR), -50);

    ui_WeatherScrn2WeekForecastPanel = lv_obj_create(ui_WeatherScreen2);
    lv_obj_set_width(ui_WeatherScrn2WeekForecastPanel, 280);
    lv_obj_set_height(ui_WeatherScrn2WeekForecastPanel, 124);
    lv_obj_set_x(ui_WeatherScrn2WeekForecastPanel, -4);
    lv_obj_set_y(ui_WeatherScrn2WeekForecastPanel, 106);
    lv_obj_set_align(ui_WeatherScrn2WeekForecastPanel, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(ui_WeatherScrn2WeekForecastPanel, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(ui_WeatherScrn2WeekForecastPanel, LV_FLEX_ALIGN_START, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_START);
    lv_obj_set_scrollbar_mode(ui_WeatherScrn2WeekForecastPanel, LV_SCROLLBAR_MODE_ON);
    lv_obj_set_scroll_dir(ui_WeatherScrn2WeekForecastPanel, LV_DIR_VER);
    lv_obj_set_style_bg_color(ui_WeatherScrn2WeekForecastPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScrn2WeekForecastPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_WeatherScrn2WeekForecastPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScrn2WeekForecastPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeekForecastUnit = ui_WeekForecastUnit_create(ui_WeatherScrn2WeekForecastPanel);
    lv_obj_set_x(ui_WeekForecastUnit, -101);
    lv_obj_set_y(ui_WeekForecastUnit, 25);

    ui_WeekForecastUnit1 = ui_WeekForecastUnit_create(ui_WeatherScrn2WeekForecastPanel);
    lv_obj_set_x(ui_WeekForecastUnit1, -101);
    lv_obj_set_y(ui_WeekForecastUnit1, 26);

    lv_image_set_src(ui_comp_get_child(ui_WeekForecastUnit1, UI_COMP_WEEKFORECASTUNIT_WEEKWEATHERICON),
                     &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit1, UI_COMP_WEEKFORECASTUNIT_DAYLABEL), "Wed");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit1, UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL), "25°");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit1, UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL), "19°");

    ui_WeekForecastUnit2 = ui_WeekForecastUnit_create(ui_WeatherScrn2WeekForecastPanel);
    lv_obj_set_x(ui_WeekForecastUnit2, -101);
    lv_obj_set_y(ui_WeekForecastUnit2, 26);

    lv_image_set_src(ui_comp_get_child(ui_WeekForecastUnit2, UI_COMP_WEEKFORECASTUNIT_WEEKWEATHERICON),
                     &ui_img_weather_cloud_png);

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit2, UI_COMP_WEEKFORECASTUNIT_DAYLABEL), "Thu");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit2, UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL), "26°");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit2, UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL), "19°");

    ui_WeekForecastUnit3 = ui_WeekForecastUnit_create(ui_WeatherScrn2WeekForecastPanel);
    lv_obj_set_x(ui_WeekForecastUnit3, -101);
    lv_obj_set_y(ui_WeekForecastUnit3, 26);

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit3, UI_COMP_WEEKFORECASTUNIT_DAYLABEL), "Fri");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit3, UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL), "25°");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit3, UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL), "16°");

    ui_WeekForecastUnit4 = ui_WeekForecastUnit_create(ui_WeatherScrn2WeekForecastPanel);
    lv_obj_set_x(ui_WeekForecastUnit4, -101);
    lv_obj_set_y(ui_WeekForecastUnit4, 26);

    lv_image_set_src(ui_comp_get_child(ui_WeekForecastUnit4, UI_COMP_WEEKFORECASTUNIT_WEEKWEATHERICON),
                     &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit4, UI_COMP_WEEKFORECASTUNIT_DAYLABEL), "Sat");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit4, UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL), "27°");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit4, UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL), "20°");

    ui_WeekForecastUnit5 = ui_WeekForecastUnit_create(ui_WeatherScrn2WeekForecastPanel);
    lv_obj_set_x(ui_WeekForecastUnit5, -101);
    lv_obj_set_y(ui_WeekForecastUnit5, 26);

    lv_image_set_src(ui_comp_get_child(ui_WeekForecastUnit5, UI_COMP_WEEKFORECASTUNIT_WEEKWEATHERICON),
                     &ui_img_weather_sun_png);

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit5, UI_COMP_WEEKFORECASTUNIT_DAYLABEL), "Sun");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit5, UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL), "29°");

    lv_label_set_text(ui_comp_get_child(ui_WeekForecastUnit5, UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL), "21°");

    ui_WeekForecastLabel = lv_label_create(ui_WeatherScreen2);
    lv_obj_set_width(ui_WeekForecastLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeekForecastLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeekForecastLabel, -4);
    lv_obj_set_y(ui_WeekForecastLabel, 27);
    lv_obj_set_align(ui_WeekForecastLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeekForecastLabel, "Week's Forecast");
    lv_obj_set_style_text_color(ui_WeekForecastLabel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_WeekForecastLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_WeekForecastLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen2SliderPanel = lv_obj_create(ui_WeatherScreen2);
    lv_obj_set_width(ui_WeatherScreen2SliderPanel, 49);
    lv_obj_set_height(ui_WeatherScreen2SliderPanel, 18);
    lv_obj_set_x(ui_WeatherScreen2SliderPanel, 5);
    lv_obj_set_y(ui_WeatherScreen2SliderPanel, 202);
    lv_obj_set_align(ui_WeatherScreen2SliderPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WeatherScreen2SliderPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreen2SliderPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_WeatherScreen2SliderPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen2SliderPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_WeatherScreen2SliderPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_WeatherScreen2SliderPanel, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScreen2SliderPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_SliderDot1 = lv_obj_create(ui_WeatherScreen2SliderPanel);
    lv_obj_set_width(ui_SliderDot1, 10);
    lv_obj_set_height(ui_SliderDot1, 10);
    lv_obj_set_x(ui_SliderDot1, 14);
    lv_obj_set_y(ui_SliderDot1, 1);
    lv_obj_set_align(ui_SliderDot1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SliderDot1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderDot1, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_SliderDot1, lv_color_hex(0xF10D0D), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_SliderDot1, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_SliderDot1, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_SliderDot2 = lv_obj_create(ui_WeatherScreen2SliderPanel);
    lv_obj_set_width(ui_SliderDot2, 10);
    lv_obj_set_height(ui_SliderDot2, 10);
    lv_obj_set_x(ui_SliderDot2, -12);
    lv_obj_set_y(ui_SliderDot2, 1);
    lv_obj_set_align(ui_SliderDot2, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SliderDot2, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderDot2, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_SliderDot2, lv_color_hex(0x676767), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_SliderDot2, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_SliderDot2, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_add_event_cb(ui_WeatherScrn2HomeBtn, ui_event_WeatherScrn2HomeBtn_Button, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WeatherScreen2, ui_event_WeatherScreen2, (lv_event_code_t)LV_EVENT_ALL, NULL);

}

void ui_WeatherScreen2_screen_destroy(void)
{
    if(ui_WeatherScreen2) lv_obj_del(ui_WeatherScreen2);

    // NULL screen variables
    ui_WeatherScreen2 = NULL;
    ui_Weather2CityNamePanel = NULL;
    ui_weather2CityLabel = NULL;
    ui_weather2DateLabel = NULL;
    ui_Weather2TodayWeatherPanel = NULL;
    ui_Weather2TodayWeatherUnitPane1 = NULL;
    ui_Weather2TodayWeatherUnitPane2 = NULL;
    ui_Weather2TodayWeatherUnitPane3 = NULL;
    ui_Weather2TodayWeatherUnitPane = NULL;
    ui_Weather2TodayWeatherUnitPane4 = NULL;
    ui_Weather2TodayWeatherUnitPane5 = NULL;
    ui_Weather2TodayWeatherUnitPane6 = NULL;
    ui_Weather2TodayWeatherUnitPane7 = NULL;
    ui_Weather2TodayWeatherUnitPane8 = NULL;
    ui_TodayForecastLabel = NULL;
    ui_WeatherScrn2HomeBtn = NULL;
    ui_WeatherScrn2WeekForecastPanel = NULL;
    ui_WeekForecastUnit = NULL;
    ui_WeekForecastUnit1 = NULL;
    ui_WeekForecastUnit2 = NULL;
    ui_WeekForecastUnit3 = NULL;
    ui_WeekForecastUnit4 = NULL;
    ui_WeekForecastUnit5 = NULL;
    ui_WeekForecastLabel = NULL;
    ui_WeatherScreen2SliderPanel = NULL;
    ui_SliderDot1 = NULL;
    ui_SliderDot2 = NULL;

}
