// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_embed_port.h"

lv_obj_t * ui_WeatherScreen1 = NULL;
lv_obj_t * ui_WeatherScreen1CityNamePanel = NULL;
lv_obj_t * ui_weather1CityLabel = NULL;
lv_obj_t * ui_weather1DateLabel = NULL;
lv_obj_t * ui_WeatherScreen1TemprtrLabel = NULL;
lv_obj_t * ui_WeatherScreen1DataPanel = NULL;
lv_obj_t * ui_weather1DescriptionLabel1 = NULL;
lv_obj_t * ui_weather1DataLabel1 = NULL;
lv_obj_t * ui_WeatherScreen1RainPanel = NULL;
lv_obj_t * ui_RainImg = NULL;
lv_obj_t * ui_RainPercentLabel = NULL;
lv_obj_t * ui_WeatherScreen1WindPanel = NULL;
lv_obj_t * ui_RainImg1 = NULL;
lv_obj_t * ui_WindSpeedLabel = NULL;
lv_obj_t * ui_WeatherScreen1SliderPanel = NULL;
lv_obj_t * ui_SliderDot1Panel = NULL;
lv_obj_t * ui_SliderDot1Panel1 = NULL;
lv_obj_t * ui_SunImg = NULL;
lv_obj_t * ui_CloudsImg = NULL;
lv_obj_t * ui_WeatherScrn1HomeBtn = NULL;
lv_obj_t * ui_WeatherScreen1WindAnimImg = NULL;
static bool s_weather1_wind_anim_started = false;
// event funtions
void ui_event_WeatherScreen1(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_SCREEN_LOADED && !s_weather1_wind_anim_started) {
        s_weather1_wind_anim_started = true;
        WindAnimation_Animation(ui_WeatherScreen1WindAnimImg, 0);
    }
    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_LEFT) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_WeatherScreen2, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_WeatherScreen2_screen_init);
    }
}

void ui_event_WeatherScrn1HomeBtn_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
}

// build funtions

void ui_WeatherScreen1_screen_init(void)
{
    ui_WeatherScreen1 = ui_embed_port_create_root();
    lv_obj_remove_flag(ui_WeatherScreen1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_WeatherScreen1, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen1, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen1CityNamePanel = lv_obj_create(ui_WeatherScreen1);
    lv_obj_set_width(ui_WeatherScreen1CityNamePanel, 162);
    lv_obj_set_height(ui_WeatherScreen1CityNamePanel, 61);
    lv_obj_set_x(ui_WeatherScreen1CityNamePanel, -77);
    lv_obj_set_y(ui_WeatherScreen1CityNamePanel, -328);
    lv_obj_set_align(ui_WeatherScreen1CityNamePanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_WeatherScreen1CityNamePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreen1CityNamePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_WeatherScreen1CityNamePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen1CityNamePanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_WeatherScreen1CityNamePanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScreen1CityNamePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_weather1CityLabel = lv_label_create(ui_WeatherScreen1CityNamePanel);
    lv_obj_set_width(ui_weather1CityLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1CityLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1CityLabel, -33);
    lv_obj_set_y(ui_weather1CityLabel, -15);
    lv_obj_set_align(ui_weather1CityLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1CityLabel, "Thailand");
    lv_obj_set_style_text_color(ui_weather1CityLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_weather1CityLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_weather1CityLabel, &ui_font_Subtitle, (lv_style_selector_t)LV_PART_MAIN);

    ui_weather1DateLabel = lv_label_create(ui_WeatherScreen1CityNamePanel);
    lv_obj_set_width(ui_weather1DateLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1DateLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1DateLabel, -8);
    lv_obj_set_y(ui_weather1DateLabel, 11);
    lv_obj_set_align(ui_weather1DateLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1DateLabel, "30. 10. 2026");
    lv_obj_set_style_text_color(ui_weather1DateLabel, lv_color_hex(0x6D6D6D), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_weather1DateLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_weather1DateLabel, &ui_font_Subtitle, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen1TemprtrLabel = lv_label_create(ui_WeatherScreen1);
    lv_obj_set_width(ui_WeatherScreen1TemprtrLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WeatherScreen1TemprtrLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WeatherScreen1TemprtrLabel, -78);
    lv_obj_set_y(ui_WeatherScreen1TemprtrLabel, -33);
    lv_obj_set_align(ui_WeatherScreen1TemprtrLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WeatherScreen1TemprtrLabel, "25°");
    lv_obj_set_style_text_color(ui_WeatherScreen1TemprtrLabel, lv_color_hex(0xEE1E1E), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_WeatherScreen1TemprtrLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_WeatherScreen1TemprtrLabel, &ui_font_Number_big, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen1DataPanel = lv_obj_create(ui_WeatherScreen1);
    lv_obj_set_width(ui_WeatherScreen1DataPanel, 244);
    lv_obj_set_height(ui_WeatherScreen1DataPanel, 61);
    lv_obj_set_x(ui_WeatherScreen1DataPanel, -70);
    lv_obj_set_y(ui_WeatherScreen1DataPanel, -115);
    lv_obj_set_align(ui_WeatherScreen1DataPanel, LV_ALIGN_BOTTOM_MID);
    lv_obj_remove_flag(ui_WeatherScreen1DataPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreen1DataPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_WeatherScreen1DataPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen1DataPanel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_WeatherScreen1DataPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScreen1DataPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_weather1DescriptionLabel1 = lv_label_create(ui_WeatherScreen1DataPanel);
    lv_obj_set_width(ui_weather1DescriptionLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1DescriptionLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1DescriptionLabel1, -48);
    lv_obj_set_y(ui_weather1DescriptionLabel1, -15);
    lv_obj_set_align(ui_weather1DescriptionLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1DescriptionLabel1, "Partly Cloudy");
    lv_obj_set_style_text_color(ui_weather1DescriptionLabel1, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_weather1DescriptionLabel1, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_weather1DescriptionLabel1, &ui_font_Subtitle, (lv_style_selector_t)LV_PART_MAIN);

    ui_weather1DataLabel1 = lv_label_create(ui_WeatherScreen1DataPanel);
    lv_obj_set_width(ui_weather1DataLabel1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_weather1DataLabel1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_weather1DataLabel1, -21);
    lv_obj_set_y(ui_weather1DataLabel1, 10);
    lv_obj_set_align(ui_weather1DataLabel1, LV_ALIGN_CENTER);
    lv_label_set_text(ui_weather1DataLabel1, "Max: 18° Min: 12°");
    lv_obj_set_style_text_color(ui_weather1DataLabel1, lv_color_hex(0x6D6D6D), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_weather1DataLabel1, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_weather1DataLabel1, &ui_font_Subtitle, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen1RainPanel = lv_obj_create(ui_WeatherScreen1);
    lv_obj_set_width(ui_WeatherScreen1RainPanel, 72);
    lv_obj_set_height(ui_WeatherScreen1RainPanel, 33);
    lv_obj_set_x(ui_WeatherScreen1RainPanel, -74);
    lv_obj_set_y(ui_WeatherScreen1RainPanel, 164);
    lv_obj_set_align(ui_WeatherScreen1RainPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WeatherScreen1RainPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreen1RainPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_WeatherScreen1RainPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen1RainPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_WeatherScreen1RainPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScreen1RainPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_RainImg = lv_image_create(ui_WeatherScreen1RainPanel);
    lv_image_set_src(ui_RainImg, &ui_img_rain_png);
    lv_obj_set_width(ui_RainImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainImg, -23);
    lv_obj_set_y(ui_RainImg, 1);
    lv_obj_set_align(ui_RainImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RainImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RainImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_RainPercentLabel = lv_label_create(ui_WeatherScreen1RainPanel);
    lv_obj_set_width(ui_RainPercentLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainPercentLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainPercentLabel, 9);
    lv_obj_set_y(ui_RainPercentLabel, 0);
    lv_obj_set_align(ui_RainPercentLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_RainPercentLabel, "18%");
    lv_obj_set_style_text_color(ui_RainPercentLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_RainPercentLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_RainPercentLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen1WindPanel = lv_obj_create(ui_WeatherScreen1);
    lv_obj_set_width(ui_WeatherScreen1WindPanel, 129);
    lv_obj_set_height(ui_WeatherScreen1WindPanel, 33);
    lv_obj_set_x(ui_WeatherScreen1WindPanel, 49);
    lv_obj_set_y(ui_WeatherScreen1WindPanel, 163);
    lv_obj_set_align(ui_WeatherScreen1WindPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WeatherScreen1WindPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreen1WindPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_WeatherScreen1WindPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen1WindPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_width(ui_WeatherScreen1WindPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScreen1WindPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_RainImg1 = lv_image_create(ui_WeatherScreen1WindPanel);
    lv_image_set_src(ui_RainImg1, &ui_img_wind_png);
    lv_obj_set_width(ui_RainImg1, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_RainImg1, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_RainImg1, -47);
    lv_obj_set_y(ui_RainImg1, 1);
    lv_obj_set_align(ui_RainImg1, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_RainImg1, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_RainImg1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_WindSpeedLabel = lv_label_create(ui_WeatherScreen1WindPanel);
    lv_obj_set_width(ui_WindSpeedLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_WindSpeedLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_WindSpeedLabel, 13);
    lv_obj_set_y(ui_WindSpeedLabel, 0);
    lv_obj_set_align(ui_WindSpeedLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_WindSpeedLabel, "54 km/h");
    lv_obj_set_style_text_color(ui_WindSpeedLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_WindSpeedLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_WindSpeedLabel, &ui_font_Title, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScreen1SliderPanel = lv_obj_create(ui_WeatherScreen1);
    lv_obj_set_width(ui_WeatherScreen1SliderPanel, 49);
    lv_obj_set_height(ui_WeatherScreen1SliderPanel, 18);
    lv_obj_set_x(ui_WeatherScreen1SliderPanel, -7);
    lv_obj_set_y(ui_WeatherScreen1SliderPanel, 204);
    lv_obj_set_align(ui_WeatherScreen1SliderPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_WeatherScreen1SliderPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_WeatherScreen1SliderPanel, 0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_WeatherScreen1SliderPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_WeatherScreen1SliderPanel, (lv_opa_t)125, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_color(ui_WeatherScreen1SliderPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_opa(ui_WeatherScreen1SliderPanel, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_WeatherScreen1SliderPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_SliderDot1Panel = lv_obj_create(ui_WeatherScreen1SliderPanel);
    lv_obj_set_width(ui_SliderDot1Panel, 10);
    lv_obj_set_height(ui_SliderDot1Panel, 10);
    lv_obj_set_x(ui_SliderDot1Panel, -12);
    lv_obj_set_y(ui_SliderDot1Panel, 0);
    lv_obj_set_align(ui_SliderDot1Panel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SliderDot1Panel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderDot1Panel, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_SliderDot1Panel, lv_color_hex(0xF51111), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_SliderDot1Panel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_SliderDot1Panel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_SliderDot1Panel1 = lv_obj_create(ui_WeatherScreen1SliderPanel);
    lv_obj_set_width(ui_SliderDot1Panel1, 10);
    lv_obj_set_height(ui_SliderDot1Panel1, 10);
    lv_obj_set_x(ui_SliderDot1Panel1, 12);
    lv_obj_set_y(ui_SliderDot1Panel1, 0);
    lv_obj_set_align(ui_SliderDot1Panel1, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_SliderDot1Panel1, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_radius(ui_SliderDot1Panel1, 10, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_SliderDot1Panel1, lv_color_hex(0x676767), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_SliderDot1Panel1, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_SliderDot1Panel1, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_SunImg = lv_image_create(ui_WeatherScreen1);
    lv_image_set_src(ui_SunImg, &ui_img_sun_png);
    lv_obj_set_width(ui_SunImg, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_SunImg, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_SunImg, 157);
    lv_obj_set_y(ui_SunImg, -62);
    lv_obj_set_align(ui_SunImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_SunImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_SunImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    ui_CloudsImg = lv_image_create(ui_WeatherScreen1);
    lv_image_set_src(ui_CloudsImg, &ui_img_visio_clouds_no_bg_152_192_png);
    lv_obj_set_width(ui_CloudsImg, 255);
    lv_obj_set_height(ui_CloudsImg, 192);
    lv_obj_set_x(ui_CloudsImg, 208);
    lv_obj_set_y(ui_CloudsImg, -47);
    lv_obj_set_align(ui_CloudsImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_CloudsImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_CloudsImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_CloudsImg, LV_IMAGE_ALIGN_TILE);
    lv_obj_set_style_blend_mode(ui_CloudsImg, LV_BLEND_MODE_ADDITIVE, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_opa(ui_CloudsImg, 200, (lv_style_selector_t)LV_PART_MAIN);

    ui_WeatherScrn1HomeBtn = ui_Button_create(ui_WeatherScreen1);
    lv_obj_set_x(ui_WeatherScrn1HomeBtn, 145);
    lv_obj_set_y(ui_WeatherScrn1HomeBtn, 125);

    lv_image_set_src(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNICON), &ui_img_house_png);
    lv_obj_set_x(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNICON), -3);
    lv_obj_set_y(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNICON), -11);

    lv_image_set_src(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNBAR), &ui_img_btn_bg_3_png);
    lv_obj_set_x(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNBAR), 13);
    lv_obj_set_y(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNBAR), 3);
    lv_image_set_rotation(ui_comp_get_child(ui_WeatherScrn1HomeBtn, UI_COMP_BUTTON_BTNBAR), 30);

    ui_WeatherScreen1WindAnimImg = lv_image_create(ui_WeatherScreen1);
    lv_image_set_src(ui_WeatherScreen1WindAnimImg, &ui_img_wind_animation_no_bg_150_140_png);
    lv_obj_set_width(ui_WeatherScreen1WindAnimImg, 299);
    lv_obj_set_height(ui_WeatherScreen1WindAnimImg, 136);
    lv_obj_set_x(ui_WeatherScreen1WindAnimImg, 149);
    lv_obj_set_y(ui_WeatherScreen1WindAnimImg, -3);
    lv_obj_set_align(ui_WeatherScreen1WindAnimImg, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_WeatherScreen1WindAnimImg, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(ui_WeatherScreen1WindAnimImg, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_image_set_inner_align(ui_WeatherScreen1WindAnimImg, LV_IMAGE_ALIGN_TILE);

    lv_obj_add_event_cb(ui_WeatherScrn1HomeBtn, ui_event_WeatherScrn1HomeBtn_Button, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_WeatherScreen1, ui_event_WeatherScreen1, (lv_event_code_t)LV_EVENT_ALL, NULL);

}

void ui_WeatherScreen1_screen_destroy(void)
{
    if(ui_WeatherScreen1) lv_obj_del(ui_WeatherScreen1);
    s_weather1_wind_anim_started = false;

    // NULL screen variables
    ui_WeatherScreen1 = NULL;
    ui_WeatherScreen1CityNamePanel = NULL;
    ui_weather1CityLabel = NULL;
    ui_weather1DateLabel = NULL;
    ui_WeatherScreen1TemprtrLabel = NULL;
    ui_WeatherScreen1DataPanel = NULL;
    ui_weather1DescriptionLabel1 = NULL;
    ui_weather1DataLabel1 = NULL;
    ui_WeatherScreen1RainPanel = NULL;
    ui_RainImg = NULL;
    ui_RainPercentLabel = NULL;
    ui_WeatherScreen1WindPanel = NULL;
    ui_RainImg1 = NULL;
    ui_WindSpeedLabel = NULL;
    ui_WeatherScreen1SliderPanel = NULL;
    ui_SliderDot1Panel = NULL;
    ui_SliderDot1Panel1 = NULL;
    ui_SunImg = NULL;
    ui_CloudsImg = NULL;
    ui_WeatherScrn1HomeBtn = NULL;
    ui_WeatherScreen1WindAnimImg = NULL;

}
