// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WEATHERSCREEN2_H
#define UI_WEATHERSCREEN2_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherScreen2
extern void ui_WeatherScreen2_screen_init(void);
extern void ui_WeatherScreen2_screen_destroy(void);
extern void ui_event_WeatherScreen2(lv_event_t * e);
extern lv_obj_t * ui_WeatherScreen2;
extern lv_obj_t * ui_Weather2CityNamePanel;
extern lv_obj_t * ui_weather2CityLabel;
extern lv_obj_t * ui_weather2DateLabel;
extern lv_obj_t * ui_Weather2TodayWeatherPanel;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane1;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane2;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane3;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane4;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane5;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane6;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane7;
extern lv_obj_t * ui_Weather2TodayWeatherUnitPane8;
extern lv_obj_t * ui_TodayForecastLabel;
extern void ui_event_WeatherScrn2HomeBtn_Button(lv_event_t * e);
extern lv_obj_t * ui_WeatherScrn2HomeBtn;
extern lv_obj_t * ui_WeatherScrn2WeekForecastPanel;
extern lv_obj_t * ui_WeekForecastUnit;
extern lv_obj_t * ui_WeekForecastUnit1;
extern lv_obj_t * ui_WeekForecastUnit2;
extern lv_obj_t * ui_WeekForecastUnit3;
extern lv_obj_t * ui_WeekForecastUnit4;
extern lv_obj_t * ui_WeekForecastUnit5;
extern lv_obj_t * ui_WeekForecastLabel;
extern lv_obj_t * ui_WeatherScreen2SliderPanel;
extern lv_obj_t * ui_SliderDot1;
extern lv_obj_t * ui_SliderDot2;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

