/* AUTO-GENERATED by tools/sprite_gen.py — do not edit by hand. */
#ifndef FLAPPY_SPRITES_H
#define FLAPPY_SPRITES_H

#include "lvgl.h"

LV_IMAGE_DECLARE(flappy_bird);   /* 44x29 RGB565A8 */
LV_IMAGE_DECLARE(flappy_pipe_cap);   /* 82x18 RGB565A8 */

#endif /* FLAPPY_SPRITES_H */
