/* AUTO-GENERATED by tools/sprite_gen.py — do not edit by hand. */
#ifndef PONG_SPRITES_H
#define PONG_SPRITES_H

#include "lvgl.h"

LV_IMAGE_DECLARE(pong_ball);   /* 14x14 RGB565A8 */
LV_IMAGE_DECLARE(pong_paddle);   /* 14x90 RGB565A8 */

#endif /* PONG_SPRITES_H */
