/* AUTO-GENERATED by tools/sprite_gen.py — do not edit by hand. */
#ifndef SHOOTER_SPRITES_H
#define SHOOTER_SPRITES_H

#include "lvgl.h"

LV_IMAGE_DECLARE(shooter_ship);   /* 62x28 RGB565A8 */
LV_IMAGE_DECLARE(shooter_enemy);   /* 16x14 RGB565A8 */
LV_IMAGE_DECLARE(shooter_enemy2);   /* 21x10 RGB565A8 */
LV_IMAGE_DECLARE(shooter_enemy3);   /* 18x14 RGB565A8 */
LV_IMAGE_DECLARE(shooter_boom_p1);   /* 29x24 RGB565A8 */
LV_IMAGE_DECLARE(shooter_boom_p2);   /* 29x24 RGB565A8 */
LV_IMAGE_DECLARE(shooter_boom_c1);   /* 29x24 RGB565A8 */
LV_IMAGE_DECLARE(shooter_boom_c2);   /* 29x24 RGB565A8 */
LV_IMAGE_DECLARE(shooter_boom_f1);   /* 29x24 RGB565A8 */
LV_IMAGE_DECLARE(shooter_boom_f2);   /* 29x24 RGB565A8 */

#endif /* SHOOTER_SPRITES_H */
