/* AUTO-GENERATED by tools/sprite_gen.py — do not edit by hand. */
#ifndef SNAKE_SPRITES_H
#define SNAKE_SPRITES_H

#include "lvgl.h"

LV_IMAGE_DECLARE(snake_head_r);   /* 16x16 RGB565A8 */
LV_IMAGE_DECLARE(snake_head_d);   /* 16x16 RGB565A8 */
LV_IMAGE_DECLARE(snake_head_l);   /* 16x16 RGB565A8 */
LV_IMAGE_DECLARE(snake_head_u);   /* 16x16 RGB565A8 */
LV_IMAGE_DECLARE(snake_body);   /* 16x16 RGB565A8 */
LV_IMAGE_DECLARE(snake_food);   /* 16x16 RGB565A8 */

#endif /* SNAKE_SPRITES_H */
