#
# This file is generated by ModusToolbox during the 'make getlibs' operation
# Any edits to this file will be lost the next time the library manager is run or
# the next time 'make getlibs' is run.
#
# Path to the current BSP
SEARCH_TARGET_KIT_PSE84_AI=../bsps/TARGET_KIT_PSE84_AI

# The search paths for the included middleware
SEARCH_btstack-integration=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/btstack-integration/release-v6.2.1
SEARCH_btstack=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/btstack/release-v4.1.5
SEARCH_freertos=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/freertos/release-v10.6.202
SEARCH_http-client=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/http-client/release-v1.8.1
SEARCH_mqtt=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mqtt/release-v4.7.0
SEARCH_retarget-io=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/retarget-io/release-v1.8.1
SEARCH_serial-memory=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/serial-memory/release-v3.1.0
SEARCH_wifi-core-freertos-lwip-mbedtls=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wifi-core-freertos-lwip-mbedtls/release-v3.1.1
SEARCH_abstraction-rtos=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/abstraction-rtos/release-v1.12.0
SEARCH_async-transfer=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/async-transfer/release-v1.1.0
SEARCH_aws-iot-device-sdk-embedded-C=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/aws-iot-device-sdk-embedded-C/202103.00
SEARCH_aws-iot-device-sdk-port=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/aws-iot-device-sdk-port/release-v2.7.0
SEARCH_bt-fw-mur-cyw55513=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/bt-fw-mur-cyw55513/release-v1.0.0
SEARCH_clib-support=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/clib-support/release-v1.8.0
SEARCH_cmsis=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cmsis/release-v6.1.0
SEARCH_connectivity-utilities=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/connectivity-utilities/release-v4.5.2
SEARCH_core-lib=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-lib/release-v1.6.0
SEARCH_core-make=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/core-make/release-v3.8.0
SEARCH_cy-mbedtls-acceleration=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/cy-mbedtls-acceleration/release-v3.0.0
SEARCH_ifx-mbedtls=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/ifx-mbedtls/release-v3.6.400
SEARCH_lwip-freertos-integration=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/lwip-freertos-integration/release-v1.2.0
SEARCH_lwip-network-interface-integration=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/lwip-network-interface-integration/release-v1.7.1
SEARCH_lwip=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/lwip/STABLE-2_1_2_RELEASE
SEARCH_mtb-dsl-pse8xxgp=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-dsl-pse8xxgp/release-v1.2.0
SEARCH_mtb-ipc=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-ipc/release-v1.2.0
SEARCH_mtb-srf=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/mtb-srf/release-v1.1.0
SEARCH_se-rt-services-utils=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/se-rt-services-utils/release-v1.2.0
SEARCH_secure-sockets=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/secure-sockets/release-v3.12.1
SEARCH_whd-bsp-integration=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/whd-bsp-integration/release-v2.5.0
SEARCH_wifi-connection-manager=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wifi-connection-manager/release-v4.1.0
SEARCH_wifi-host-driver=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wifi-host-driver/release-v5.0.8
SEARCH_wifi-resources=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wifi-resources/release-v3.0.5
SEARCH_wpa3-external-supplicant=$(patsubst %/,%,$(CY_GETLIBS_SHARED_PATH))/$(CY_GETLIBS_SHARED_NAME)/wpa3-external-supplicant/release-v1.3.1

# Search libraries added to build
SEARCH_MTB_MK+=$(SEARCH_btstack-integration)
SEARCH_MTB_MK+=$(SEARCH_btstack)
SEARCH_MTB_MK+=$(SEARCH_freertos)
SEARCH_MTB_MK+=$(SEARCH_http-client)
SEARCH_MTB_MK+=$(SEARCH_mqtt)
SEARCH_MTB_MK+=$(SEARCH_retarget-io)
SEARCH_MTB_MK+=$(SEARCH_serial-memory)
SEARCH_MTB_MK+=$(SEARCH_wifi-core-freertos-lwip-mbedtls)
SEARCH_MTB_MK+=$(SEARCH_abstraction-rtos)
SEARCH_MTB_MK+=$(SEARCH_async-transfer)
SEARCH_MTB_MK+=$(SEARCH_aws-iot-device-sdk-embedded-C)
SEARCH_MTB_MK+=$(SEARCH_aws-iot-device-sdk-port)
SEARCH_MTB_MK+=$(SEARCH_bt-fw-mur-cyw55513)
SEARCH_MTB_MK+=$(SEARCH_clib-support)
SEARCH_MTB_MK+=$(SEARCH_cmsis)
SEARCH_MTB_MK+=$(SEARCH_connectivity-utilities)
SEARCH_MTB_MK+=$(SEARCH_core-lib)
SEARCH_MTB_MK+=$(SEARCH_core-make)
SEARCH_MTB_MK+=$(SEARCH_cy-mbedtls-acceleration)
SEARCH_MTB_MK+=$(SEARCH_ifx-mbedtls)
SEARCH_MTB_MK+=$(SEARCH_lwip-freertos-integration)
SEARCH_MTB_MK+=$(SEARCH_lwip-network-interface-integration)
SEARCH_MTB_MK+=$(SEARCH_lwip)
SEARCH_MTB_MK+=$(SEARCH_mtb-dsl-pse8xxgp)
SEARCH_MTB_MK+=$(SEARCH_mtb-ipc)
SEARCH_MTB_MK+=$(SEARCH_mtb-srf)
SEARCH_MTB_MK+=$(SEARCH_se-rt-services-utils)
SEARCH_MTB_MK+=$(SEARCH_secure-sockets)
SEARCH_MTB_MK+=$(SEARCH_whd-bsp-integration)
SEARCH_MTB_MK+=$(SEARCH_wifi-connection-manager)
SEARCH_MTB_MK+=$(SEARCH_wifi-host-driver)
SEARCH_MTB_MK+=$(SEARCH_wifi-resources)
SEARCH_MTB_MK+=$(SEARCH_wpa3-external-supplicant)

-include $(CY_INTERNAL_APP_PATH)/importedbsp.mk
COMPONENTS += MW_BTSTACK_INTEGRATION
COMPONENTS += MW_BTSTACK
COMPONENTS += MW_FREERTOS
COMPONENTS += MW_HTTP_CLIENT
COMPONENTS += MW_MQTT
COMPONENTS += MW_RETARGET_IO
COMPONENTS += MW_SERIAL_MEMORY
COMPONENTS += MW_WIFI_CORE_FREERTOS_LWIP_MBEDTLS
COMPONENTS += MW_ABSTRACTION_RTOS
COMPONENTS += MW_ASYNC_TRANSFER
COMPONENTS += MW_AWS_IOT_DEVICE_SDK_EMBEDDED_C
COMPONENTS += MW_AWS_IOT_DEVICE_SDK_PORT
COMPONENTS += MW_BT_FW_MUR_CYW55513
COMPONENTS += MW_CLIB_SUPPORT
COMPONENTS += MW_CMSIS
COMPONENTS += MW_CONNECTIVITY_UTILITIES
COMPONENTS += MW_CORE_LIB
COMPONENTS += MW_CORE_MAKE
COMPONENTS += MW_CY_MBEDTLS_ACCELERATION
COMPONENTS += MW_IFX_MBEDTLS
COMPONENTS += MW_LWIP_FREERTOS_INTEGRATION
COMPONENTS += MW_LWIP_NETWORK_INTERFACE_INTEGRATION
COMPONENTS += MW_LWIP
COMPONENTS += MW_MTB_DSL_PSE8XXGP
COMPONENTS += MW_MTB_IPC
COMPONENTS += MW_MTB_SRF
COMPONENTS += MW_SE_RT_SERVICES_UTILS
COMPONENTS += MW_SECURE_SOCKETS
COMPONENTS += MW_WHD_BSP_INTEGRATION
COMPONENTS += MW_WIFI_CONNECTION_MANAGER
COMPONENTS += MW_WIFI_HOST_DRIVER
COMPONENTS += MW_WIFI_RESOURCES
COMPONENTS += MW_WPA3_EXTERNAL_SUPPLICANT

# Register map file
DEVICE_PSE846GPS2DBZC4A_SVD=$(SEARCH_mtb-dsl-pse8xxgp)/pdl/svd/pse84.svd


#
# generate make targets for the graphical editors that are specific to this project
#

modlibs:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: modlibs

CY_HELP_modlibs=Launches the Library Manager 2.70 GUI
CY_HELP_modlibs_VERBOSE=Launches the Library Manager 2.70 GUI. Check the Library Manager 2.70 User Guide for more information.
mtb_help_tool_modlibs:
	@:
	$(info $(MTB__SPACE)modlibs             $(CY_HELP_modlibs))

mtb_help_tools_end: mtb_help_tool_modlibs
mtb_help_tool_modlibs: mtb_help_tools_start
.PHONY: mtb_help_tool_modlibs

library-manager:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name library-manager
.PHONY: library-manager

CY_HELP_library-manager=Launches the Library Manager 2.70 GUI
CY_HELP_library-manager_VERBOSE=Launches the Library Manager 2.70 GUI. Check the Library Manager 2.70 User Guide for more information.
mtb_help_tool_library-manager:
	@:
	$(info $(MTB__SPACE)library-manager     $(CY_HELP_library-manager))

mtb_help_tools_end: mtb_help_tool_library-manager
mtb_help_tool_library-manager: mtb_help_tools_start
.PHONY: mtb_help_tool_library-manager

qspi-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name qspi-configurator
.PHONY: qspi-configurator

CY_HELP_qspi-configurator=Launches the QSPI Configurator 4.80 GUI for the target's cyqspi file
CY_HELP_qspi-configurator_VERBOSE=Launches the QSPI Configurator 4.80 GUI. Check the QSPI Configurator 4.80 User Guide for more information.
mtb_help_tool_qspi-configurator:
	@:
	$(info $(MTB__SPACE)qspi-configurator   $(CY_HELP_qspi-configurator))

mtb_help_tools_end: mtb_help_tool_qspi-configurator
mtb_help_tool_qspi-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_qspi-configurator

config:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: config

CY_HELP_config=Launches the Device Configurator 5.70 GUI for the target's modus file
CY_HELP_config_VERBOSE=Launches the Device Configurator 5.70 GUI. Check the Device Configurator 5.70 User Guide for more information.
mtb_help_tool_config:
	@:
	$(info $(MTB__SPACE)config              $(CY_HELP_config))

mtb_help_tools_end: mtb_help_tool_config
mtb_help_tool_config: mtb_help_tools_start
.PHONY: mtb_help_tool_config

device-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name device-configurator
.PHONY: device-configurator

CY_HELP_device-configurator=Launches the Device Configurator 5.70 GUI for the target's modus file
CY_HELP_device-configurator_VERBOSE=Launches the Device Configurator 5.70 GUI. Check the Device Configurator 5.70 User Guide for more information.
mtb_help_tool_device-configurator:
	@:
	$(info $(MTB__SPACE)device-configurator $(CY_HELP_device-configurator))

mtb_help_tools_end: mtb_help_tool_device-configurator
mtb_help_tool_device-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_device-configurator

bsp-assistant:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bsp-assistant
.PHONY: bsp-assistant

CY_HELP_bsp-assistant=Launches the BSP Assistant 1.70 GUI
CY_HELP_bsp-assistant_VERBOSE=Launches the BSP Assistant 1.70 GUI. Check the BSP Assistant 1.70 User Guide for more information.
mtb_help_tool_bsp-assistant:
	@:
	$(info $(MTB__SPACE)bsp-assistant       $(CY_HELP_bsp-assistant))

mtb_help_tools_end: mtb_help_tool_bsp-assistant
mtb_help_tool_bsp-assistant: mtb_help_tools_start
.PHONY: mtb_help_tool_bsp-assistant

config_bt:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: config_bt

CY_HELP_config_bt=Launches the Bluetooth® Configurator 3.60 GUI for the target's cybt file
CY_HELP_config_bt_VERBOSE=Launches the Bluetooth® Configurator 3.60 GUI. Check the Bluetooth® Configurator 3.60 User Guide for more information.
mtb_help_tool_config_bt:
	@:
	$(info $(MTB__SPACE)config_bt           $(CY_HELP_config_bt))

mtb_help_tools_end: mtb_help_tool_config_bt
mtb_help_tool_config_bt: mtb_help_tools_start
.PHONY: mtb_help_tool_config_bt

bt-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name bt-configurator
.PHONY: bt-configurator

CY_HELP_bt-configurator=Launches the Bluetooth® Configurator 3.60 GUI for the target's cybt file
CY_HELP_bt-configurator_VERBOSE=Launches the Bluetooth® Configurator 3.60 GUI. Check the Bluetooth® Configurator 3.60 User Guide for more information.
mtb_help_tool_bt-configurator:
	@:
	$(info $(MTB__SPACE)bt-configurator     $(CY_HELP_bt-configurator))

mtb_help_tools_end: mtb_help_tool_bt-configurator
mtb_help_tool_bt-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_bt-configurator

smartio-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name smartio-configurator
.PHONY: smartio-configurator

CY_HELP_smartio-configurator=Launches the Smart I/O Configurator 4.70 GUI for the target's modus file
CY_HELP_smartio-configurator_VERBOSE=Launches the Smart I/O Configurator 4.70 GUI. Check the Smart I/O Configurator 4.70 User Guide for more information.
mtb_help_tool_smartio-configurator:
	@:
	$(info $(MTB__SPACE)smartio-configurator $(CY_HELP_smartio-configurator))

mtb_help_tools_end: mtb_help_tool_smartio-configurator
mtb_help_tool_smartio-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_smartio-configurator

config_ml:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ml-configurator
.PHONY: config_ml

CY_HELP_config_ml=Launches the ML Configurator 3.0 GUI for the target's mtbml file
CY_HELP_config_ml_VERBOSE=Launches the ML Configurator 3.0 GUI. Check the ML Configurator 3.0 User Guide for more information.
mtb_help_tool_config_ml:
	@:
	$(info $(MTB__SPACE)config_ml           $(CY_HELP_config_ml))

mtb_help_tools_end: mtb_help_tool_config_ml
mtb_help_tool_config_ml: mtb_help_tools_start
.PHONY: mtb_help_tool_config_ml

ml-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name ml-configurator
.PHONY: ml-configurator

CY_HELP_ml-configurator=Launches the ML Configurator 3.0 GUI for the target's mtbml file
CY_HELP_ml-configurator_VERBOSE=Launches the ML Configurator 3.0 GUI. Check the ML Configurator 3.0 User Guide for more information.
mtb_help_tool_ml-configurator:
	@:
	$(info $(MTB__SPACE)ml-configurator     $(CY_HELP_ml-configurator))

mtb_help_tools_end: mtb_help_tool_ml-configurator
mtb_help_tool_ml-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_ml-configurator

edge-protect-configurator:
	$(CY_TOOL_mtblaunch_EXE_ABS) --project . --short-name edge-protect-configurator
.PHONY: edge-protect-configurator

CY_HELP_edge-protect-configurator=Launches the Edge Protect Configurator 1.20 GUI for the target's edgeprotect file
CY_HELP_edge-protect-configurator_VERBOSE=Launches the Edge Protect Configurator 1.20 GUI. Check the Edge Protect Configurator 1.20 User Guide for more information.
mtb_help_tool_edge-protect-configurator:
	@:
	$(info $(MTB__SPACE)edge-protect-configurator $(CY_HELP_edge-protect-configurator))

mtb_help_tools_end: mtb_help_tool_edge-protect-configurator
mtb_help_tool_edge-protect-configurator: mtb_help_tools_start
.PHONY: mtb_help_tool_edge-protect-configurator

.PHONY: mtb_help_tools_start mtb_help_tools_end
