// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_ANALOGSCREEN_H
#define UI_ANALOGSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_AnalogScreen
extern void ui_AnalogScreen_screen_init(void);
extern void ui_AnalogScreen_screen_destroy(void);
extern void ui_event_AnalogScreen(lv_event_t * e);
extern lv_obj_t * ui_AnalogScreen;
extern lv_obj_t * ui_AnalogScreenBatteryPanel;
extern lv_obj_t * ui_AnalogScreenBatteryLevel;
extern lv_obj_t * ui_AnalogScreenBatteryImg;
extern lv_obj_t * ui_AnalogScreenDatePanel;
extern lv_obj_t * ui_AnalogScreenDateLabel;
extern lv_obj_t * ui_AnalogScreenMonthLabel;
extern lv_obj_t * ui_AnalogScreenYearLabel;
extern lv_obj_t * ui_AnalogScreenDayLabel;
extern lv_obj_t * ui_AnalogScreenWeatherPanel;
extern lv_obj_t * ui_AnalogScreenWeatherIcon;
extern lv_obj_t * ui_AnalogScreenWeatherLabel;
extern void ui_event_AnalogScreenBrightnessArc(lv_event_t * e);
extern lv_obj_t * ui_AnalogScreenBrightnessArc;
extern lv_obj_t * ui_AnalogBrightnessIcon;
extern lv_obj_t * ui_AnalogScreenStepsPanel;
extern lv_obj_t * ui_AnalogScreenStepImg;
extern lv_obj_t * ui_AnalogScreenStepsCountLabel;
extern lv_obj_t * ui_AnalogScreenBrightnessPercentLabel;
extern lv_obj_t * ui_AnalogScreenClockPanel;
extern lv_obj_t * ui_AnalogScreenSecHand;
extern lv_obj_t * ui_AnalogScreenMinHand;
extern lv_obj_t * ui_AnalogScreenHourHand;
extern void ui_event_AnalogScreenWeatherButton_Button(lv_event_t * e);
extern lv_obj_t * ui_AnalogScreenWeatherButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

