// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Weather2TodayWeatherUnitPane

lv_obj_t * ui_Weather2TodayWeatherUnitPane_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Weather2TodayWeatherUnitPane;
    cui_Weather2TodayWeatherUnitPane = lv_obj_create(comp_parent);
    lv_obj_set_height(cui_Weather2TodayWeatherUnitPane, 108);
    lv_obj_set_width(cui_Weather2TodayWeatherUnitPane, LV_SIZE_CONTENT);   /// 82
    lv_obj_set_x(cui_Weather2TodayWeatherUnitPane, 0);
    lv_obj_set_y(cui_Weather2TodayWeatherUnitPane, 0);
    lv_obj_set_align(cui_Weather2TodayWeatherUnitPane, LV_ALIGN_CENTER);
    lv_obj_set_flex_flow(cui_Weather2TodayWeatherUnitPane, LV_FLEX_FLOW_COLUMN);
    lv_obj_set_flex_align(cui_Weather2TodayWeatherUnitPane, LV_FLEX_ALIGN_CENTER, LV_FLEX_ALIGN_CENTER,
                          LV_FLEX_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Weather2TodayWeatherUnitPane, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Weather2TodayWeatherUnitPane, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cui_Weather2TodayWeatherUnitPane, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(cui_Weather2TodayWeatherUnitPane, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_t * cui_TimeLabel;
    cui_TimeLabel = lv_label_create(cui_Weather2TodayWeatherUnitPane);
    lv_obj_set_width(cui_TimeLabel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TimeLabel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_TimeLabel, LV_ALIGN_CENTER);
    lv_label_set_text(cui_TimeLabel, "NOW");
    lv_obj_set_style_text_color(cui_TimeLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(cui_TimeLabel, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_t * cui_TodayWeatherIcon;
    cui_TodayWeatherIcon = lv_image_create(cui_Weather2TodayWeatherUnitPane);
    lv_image_set_src(cui_TodayWeatherIcon, &ui_img_weather_sun_cloud_png);
    lv_obj_set_width(cui_TodayWeatherIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_TodayWeatherIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_TodayWeatherIcon, LV_ALIGN_CENTER);
    lv_image_set_scale(cui_TodayWeatherIcon, 200);
    lv_obj_add_flag(cui_TodayWeatherIcon,(lv_obj_flag_t) LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_TodayWeatherIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_Label3;
    cui_Label3 = lv_label_create(cui_Weather2TodayWeatherUnitPane);
    lv_obj_set_width(cui_Label3, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_Label3, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_align(cui_Label3, LV_ALIGN_CENTER);
    lv_label_set_text(cui_Label3, "25°");
    lv_obj_set_style_text_color(cui_Label3, lv_color_hex(0xFFFFFF), LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_opa(cui_Label3, (lv_opa_t)255, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);
    lv_obj_set_style_text_font(cui_Label3, &lv_font_montserrat_20, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_WEATHER2TODAYWEATHERUNITPANE_NUM);
    children[UI_COMP_WEATHER2TODAYWEATHERUNITPANE_WEATHER2TODAYWEATHERUNITPANE] = cui_Weather2TodayWeatherUnitPane;
    children[UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TIMELABEL] = cui_TimeLabel;
    children[UI_COMP_WEATHER2TODAYWEATHERUNITPANE_TODAYWEATHERICON] = cui_TodayWeatherIcon;
    children[UI_COMP_WEATHER2TODAYWEATHERUNITPANE_LABEL3] = cui_Label3;
    lv_obj_add_event_cb(cui_Weather2TodayWeatherUnitPane, get_component_child_event_cb, (lv_event_code_t)LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Weather2TodayWeatherUnitPane, del_component_child_event_cb, (lv_event_code_t)LV_EVENT_DELETE, children);
    ui_comp_Weather2TodayWeatherUnitPane_create_hook(cui_Weather2TodayWeatherUnitPane);
    return cui_Weather2TodayWeatherUnitPane;
}

