// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

void ui_comp_Button_create_hook(lv_obj_t * comp)
{
}

void ui_comp_Weather2TodayWeatherUnitPane_create_hook(lv_obj_t * comp)
{
}

void ui_comp_WeekForecastUnit_create_hook(lv_obj_t * comp)
{
}
