// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"

// COMPONENT Button

lv_obj_t * ui_Button_create(lv_obj_t * comp_parent)
{

    lv_obj_t * cui_Button;
    cui_Button = lv_obj_create(comp_parent);
    lv_obj_set_width(cui_Button, 62);
    lv_obj_set_height(cui_Button, 50);
    lv_obj_set_x(cui_Button, 153);
    lv_obj_set_y(cui_Button, 90);
    lv_obj_set_align(cui_Button, LV_ALIGN_CENTER);
    lv_obj_remove_flag(cui_Button, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(cui_Button, lv_color_hex(0x000000), LV_PART_MAIN);
    lv_obj_set_style_bg_opa(cui_Button, (lv_opa_t)0, LV_PART_MAIN);
    lv_obj_set_style_border_width(cui_Button, 0, LV_PART_MAIN);
    lv_obj_set_style_border_side(cui_Button, LV_BORDER_SIDE_NONE, LV_PART_MAIN);

    lv_obj_t * cui_BtnIcon;
    cui_BtnIcon = lv_image_create(cui_Button);
    lv_obj_set_width(cui_BtnIcon, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_BtnIcon, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_BtnIcon, 0);
    lv_obj_set_y(cui_BtnIcon, -4);
    lv_obj_set_align(cui_BtnIcon, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BtnIcon, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_BtnIcon, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t * cui_BtnBar;
    cui_BtnBar = lv_image_create(cui_Button);
    lv_image_set_src(cui_BtnBar, &ui_img_btn_bg_4_png);
    lv_obj_set_width(cui_BtnBar, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(cui_BtnBar, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(cui_BtnBar, 1);
    lv_obj_set_y(cui_BtnBar, 13);
    lv_obj_set_align(cui_BtnBar, LV_ALIGN_CENTER);
    lv_obj_add_flag(cui_BtnBar, (lv_obj_flag_t)LV_OBJ_FLAG_ADV_HITTEST);     /// Flags
    lv_obj_remove_flag(cui_BtnBar, LV_OBJ_FLAG_SCROLLABLE);      /// Flags

    lv_obj_t ** children = lv_malloc(sizeof(lv_obj_t *) * _UI_COMP_BUTTON_NUM);
    children[UI_COMP_BUTTON_BUTTON] = cui_Button;
    children[UI_COMP_BUTTON_BTNICON] = cui_BtnIcon;
    children[UI_COMP_BUTTON_BTNBAR] = cui_BtnBar;
    lv_obj_add_event_cb(cui_Button, get_component_child_event_cb, (lv_event_code_t)LV_EVENT_GET_COMP_CHILD, children);
    lv_obj_add_event_cb(cui_Button, del_component_child_event_cb, (lv_event_code_t)LV_EVENT_DELETE, children);
    ui_comp_Button_create_hook(cui_Button);
    return cui_Button;
}

