// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_BUTTON_H
#define _UI_COMP_BUTTON_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT Button
#define UI_COMP_BUTTON_BUTTON 0
#define UI_COMP_BUTTON_BTNICON 1
#define UI_COMP_BUTTON_BTNBAR 2
#define _UI_COMP_BUTTON_NUM 3
lv_obj_t * ui_Button_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
