// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_COMP_WEEKFORECASTUNIT_H
#define _UI_COMP_WEEKFORECASTUNIT_H

#include "ui.h"

#ifdef __cplusplus
extern "C" {
#endif

// COMPONENT WeekForecastUnit
#define UI_COMP_WEEKFORECASTUNIT_WEEKFORECASTUNIT 0
#define UI_COMP_WEEKFORECASTUNIT_WEEKWEATHERICON 1
#define UI_COMP_WEEKFORECASTUNIT_DAYLABEL 2
#define UI_COMP_WEEKFORECASTUNIT_TEMPMAXLABEL 3
#define UI_COMP_WEEKFORECASTUNIT_MINTEMPLABEL 4
#define _UI_COMP_WEEKFORECASTUNIT_NUM 5
lv_obj_t * ui_WeekForecastUnit_create(lv_obj_t * comp_parent);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
