// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_DIGITALSCREEN_H
#define UI_DIGITALSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_DigitalScreen
extern void ui_DigitalScreen_screen_init(void);
extern void ui_DigitalScreen_screen_destroy(void);
extern void ui_event_DigitalScreen(lv_event_t * e);
extern lv_obj_t * ui_DigitalScreen;
extern lv_obj_t * ui_DigiScreenBatteryPanel;
extern lv_obj_t * ui_DigiScreenBatteryLevel;
extern lv_obj_t * ui_DigiScreenBatteryImg;
extern lv_obj_t * ui_DigiScreenDatePanel;
extern lv_obj_t * ui_DigiScreenDateLabel;
extern lv_obj_t * ui_DigiScreenMonthLabel;
extern lv_obj_t * ui_DigiScreenYearLabel;
extern lv_obj_t * ui_DigiScreenDayLabel;
extern lv_obj_t * ui_DigiScreenTimePanel;
extern lv_obj_t * ui_DigiScreenHourLabel;
extern lv_obj_t * ui_DigiScreenClockDots;
extern lv_obj_t * ui_DigiScreenMinLabel;
extern lv_obj_t * ui_DigiScreenWeatherPanel;
extern lv_obj_t * ui_WeatherIcon;
extern lv_obj_t * ui_WeatherLabel;
extern void ui_event_DigiScreenBrightnessArc(lv_event_t * e);
extern lv_obj_t * ui_DigiScreenBrightnessArc;
extern lv_obj_t * ui_DigiScreenBrightnessPercentLabel;
extern lv_obj_t * ui_BrightnessIcon;
extern lv_obj_t * ui_DigiScreenStepsPanel;
extern lv_obj_t * ui_DigiScreenStepsCountLabel;
extern lv_obj_t * ui_DigitalScreenStepImg;
extern void ui_event_WeatherButton_Button(lv_event_t * e);
extern lv_obj_t * ui_WeatherButton;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

