// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.4.0
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef _UI_EVENTS_H
#define _UI_EVENTS_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdint.h>
#include "cy_rtc.h"

void ui_time_cb(cy_stc_rtc_config_t rtc_date_time);
void ui_step_cb(uint32_t count);
void ui_health_screen_cb(void);

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif
