// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_HEALTHSCREEN_H
#define UI_HEALTHSCREEN_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_HealthScreen
extern void ui_HealthScreen_screen_init(void);
extern void ui_HealthScreen_screen_destroy(void);
extern void ui_event_HealthScreen(lv_event_t * e);
extern lv_obj_t * ui_HealthScreen;
extern lv_obj_t * ui_Label1;
extern lv_obj_t * ui_BloodPressureSYSPanel;
extern lv_obj_t * ui_BloodPressureSYSLabel;
extern lv_obj_t * ui_BloodPressureUnitLabel;
extern lv_obj_t * ui_BloodPressureDIAPanel;
extern lv_obj_t * ui_BloodPressureDIALabel;
extern lv_obj_t * ui_BloodPressureDIAUnitLabel;
extern lv_obj_t * ui_BloodPressureSYSValueLabel;
extern lv_obj_t * ui_BloodPressureDIAValueLabel;
extern lv_obj_t * ui_HeartAnimPanel;
extern lv_obj_t * ui_HeartImgContainPanel;
extern lv_obj_t * ui_HeartImg;
extern lv_obj_t * ui_HeartBeatAnimSpinner;
extern lv_obj_t * ui_HeartRateLabel;
extern lv_obj_t * ui_HeartBeatValueLabel;
extern lv_obj_t * ui_HeartIcon;
extern lv_obj_t * ui_HeartBeatUnitLabel;
extern void ui_event_HealthScrnHomeBtn_Button(lv_event_t * e);
extern lv_obj_t * ui_HealthScrnHomeBtn;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

