// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#include "ui.h"
#include "ui_embed_port.h"

lv_obj_t * ui_MusicScreen = NULL;
lv_obj_t * ui_MusicTitleLabel = NULL;
lv_obj_t * ui_MusicPrevButtonPanel = NULL;
lv_obj_t * ui_MusicPausePlayButtonPanel = NULL;
lv_obj_t * ui_MusicNextButtonPanel = NULL;
lv_obj_t * ui_MusicScreenVolumePanel = NULL;
lv_obj_t * ui_MusicScreenVolumeArc = NULL;
lv_obj_t * ui_MusicScreenVolumeNameLabel = NULL;
lv_obj_t * ui_MusicScreenVolumePercent = NULL;
lv_obj_t * ui_MusicTimePanel = NULL;
lv_obj_t * ui_MusicCurrTimeMinPanel = NULL;
lv_obj_t * ui_MusicCurrTimeDotsPanel = NULL;
lv_obj_t * ui_MusicCurrTimeSecPanel = NULL;
lv_obj_t * ui_MusicTimeSlashPanel = NULL;
lv_obj_t * ui_MusicTotalTimeMinPanel = NULL;
lv_obj_t * ui_MusicTotalTimeDotsPanel = NULL;
lv_obj_t * ui_MusicTotalTimeSecPanel = NULL;
lv_obj_t * ui_MusicScreenHomeBtnPanel = NULL;
// event funtions
void ui_event_MusicScreen(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(!ui_embed_port_is_enabled() &&
       event_code == LV_EVENT_GESTURE && lv_indev_active() &&
       lv_indev_get_gesture_dir(lv_indev_active()) == LV_DIR_BOTTOM) {
        lv_indev_wait_release(lv_indev_active());
        _ui_screen_change(&ui_HealthScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_HealthScreen_screen_init);
    }
}

void ui_event_MusicScreenVolumeArc(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);
    lv_obj_t * target = lv_event_get_target(e);

    if(event_code == LV_EVENT_VALUE_CHANGED) {
        _ui_arc_set_text_value(ui_MusicScreenVolumePercent, target, "", "%");
    }
}

void ui_event_MusicScreenHomeBtnPanel_Button(lv_event_t * e)
{
    lv_event_code_t event_code = lv_event_get_code(e);

    if(event_code == LV_EVENT_CLICKED) {
        _ui_screen_change(&ui_DigitalScreen, LV_SCR_LOAD_ANIM_FADE_ON, 0, 0, &ui_DigitalScreen_screen_init);
    }
}

// build funtions

void ui_MusicScreen_screen_init(void)
{
    ui_MusicScreen = ui_embed_port_create_root();
    lv_obj_remove_flag(ui_MusicScreen, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicScreen, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicScreen, (lv_opa_t)255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_src(ui_MusicScreen, &ui_img_white_dot_watch_face_bg_png, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicTitleLabel = lv_label_create(ui_MusicScreen);
    lv_obj_set_width(ui_MusicTitleLabel, 297);
    lv_obj_set_height(ui_MusicTitleLabel, 40);
    lv_obj_set_x(ui_MusicTitleLabel, 0);
    lv_obj_set_y(ui_MusicTitleLabel, -111);
    lv_obj_set_align(ui_MusicTitleLabel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_MusicTitleLabel,
                           ui_embed_port_is_enabled() ? LV_LABEL_LONG_CLIP : LV_LABEL_LONG_SCROLL);
    lv_label_set_text(ui_MusicTitleLabel, "Waiting for Love - John Doe");
    lv_obj_set_style_text_color(ui_MusicTitleLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicTitleLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicTitleLabel, &lv_font_montserrat_36, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicTitleLabel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN );
    lv_obj_set_style_bg_opa(ui_MusicTitleLabel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicPrevButtonPanel = lv_obj_create(ui_MusicScreen);
    lv_obj_set_width(ui_MusicPrevButtonPanel, 57);
    lv_obj_set_height(ui_MusicPrevButtonPanel, 65);
    lv_obj_set_x(ui_MusicPrevButtonPanel, -114);
    lv_obj_set_y(ui_MusicPrevButtonPanel, -30);
    lv_obj_set_align(ui_MusicPrevButtonPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MusicPrevButtonPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicPrevButtonPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicPrevButtonPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_src(ui_MusicPrevButtonPanel, &ui_img_music_prev_button_50_60_no_bg_png,
                                  (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_MusicPrevButtonPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicPausePlayButtonPanel = lv_obj_create(ui_MusicScreen);
    lv_obj_set_width(ui_MusicPausePlayButtonPanel, 57);
    lv_obj_set_height(ui_MusicPausePlayButtonPanel, 65);
    lv_obj_set_x(ui_MusicPausePlayButtonPanel, -4);
    lv_obj_set_y(ui_MusicPausePlayButtonPanel, -31);
    lv_obj_set_align(ui_MusicPausePlayButtonPanel, LV_ALIGN_CENTER);
    lv_obj_add_flag(ui_MusicPausePlayButtonPanel, (lv_obj_flag_t)LV_OBJ_FLAG_CHECKABLE);     /// Flags
    lv_obj_remove_flag(ui_MusicPausePlayButtonPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicPausePlayButtonPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicPausePlayButtonPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_src(ui_MusicPausePlayButtonPanel, &ui_img_music_pause_button_50_50_no_bg_png,
                                  (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_MusicPausePlayButtonPanel, LV_BORDER_SIDE_NONE, LV_PART_MAIN | (lv_style_selector_t)LV_STATE_DEFAULT);

    ui_MusicNextButtonPanel = lv_obj_create(ui_MusicScreen);
    lv_obj_set_width(ui_MusicNextButtonPanel, 57);
    lv_obj_set_height(ui_MusicNextButtonPanel, 65);
    lv_obj_set_x(ui_MusicNextButtonPanel, 111);
    lv_obj_set_y(ui_MusicNextButtonPanel, -33);
    lv_obj_set_align(ui_MusicNextButtonPanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MusicNextButtonPanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicNextButtonPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicNextButtonPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_image_src(ui_MusicNextButtonPanel, &ui_img_music_next_button_50_50_no_bg_png,
                                  (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_MusicNextButtonPanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicScreenVolumePanel = lv_obj_create(ui_MusicScreen);
    lv_obj_set_width(ui_MusicScreenVolumePanel, 236);
    lv_obj_set_height(ui_MusicScreenVolumePanel, 207);
    lv_obj_set_x(ui_MusicScreenVolumePanel, -185);
    lv_obj_set_y(ui_MusicScreenVolumePanel, 109);
    lv_obj_set_align(ui_MusicScreenVolumePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MusicScreenVolumePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicScreenVolumePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicScreenVolumePanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_MusicScreenVolumePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicScreenVolumeArc = lv_arc_create(ui_MusicScreenVolumePanel);
    lv_obj_set_width(ui_MusicScreenVolumeArc, 387);
    lv_obj_set_height(ui_MusicScreenVolumeArc, 372);
    lv_obj_set_x(ui_MusicScreenVolumeArc, 182);
    lv_obj_set_y(ui_MusicScreenVolumeArc, -94);
    lv_obj_set_align(ui_MusicScreenVolumeArc, LV_ALIGN_CENTER);
    lv_arc_set_value(ui_MusicScreenVolumeArc, 80);
    lv_arc_set_bg_angles(ui_MusicScreenVolumeArc, 10, 80);
    lv_arc_set_rotation(ui_MusicScreenVolumeArc, 100);
    lv_obj_set_style_bg_color(ui_MusicScreenVolumeArc, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicScreenVolumeArc, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_color(ui_MusicScreenVolumeArc, lv_color_hex(0x303030), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_opa(ui_MusicScreenVolumeArc, 255, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_width(ui_MusicScreenVolumeArc, 7, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_arc_rounded(ui_MusicScreenVolumeArc, true, (lv_style_selector_t)LV_PART_MAIN);

    lv_obj_set_style_arc_color(ui_MusicScreenVolumeArc, lv_color_hex(0xB0E14A), LV_PART_INDICATOR);
    lv_obj_set_style_arc_opa(ui_MusicScreenVolumeArc, 255, LV_PART_INDICATOR);
    lv_obj_set_style_arc_width(ui_MusicScreenVolumeArc, 7, LV_PART_INDICATOR);
    lv_obj_set_style_arc_rounded(ui_MusicScreenVolumeArc, true, LV_PART_INDICATOR);

    lv_obj_set_style_bg_color(ui_MusicScreenVolumeArc, lv_color_hex(0xB0E14A), LV_PART_KNOB);
    lv_obj_set_style_bg_opa(ui_MusicScreenVolumeArc, (lv_opa_t)255, LV_PART_KNOB);

    ui_MusicScreenVolumeNameLabel = lv_label_create(ui_MusicScreenVolumePanel);
    lv_obj_set_width(ui_MusicScreenVolumeNameLabel, 82);
    lv_obj_set_height(ui_MusicScreenVolumeNameLabel, 26);
    lv_obj_set_x(ui_MusicScreenVolumeNameLabel, 81);
    lv_obj_set_y(ui_MusicScreenVolumeNameLabel, -5);
    lv_obj_set_align(ui_MusicScreenVolumeNameLabel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicScreenVolumeNameLabel, "Volume");
    lv_obj_set_style_text_color(ui_MusicScreenVolumeNameLabel, lv_color_hex(0xFFFFFF), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicScreenVolumeNameLabel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicScreenVolumeNameLabel, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicScreenVolumeNameLabel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicScreenVolumeNameLabel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicScreenVolumePercent = lv_label_create(ui_MusicScreenVolumePanel);
    lv_obj_set_width(ui_MusicScreenVolumePercent, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicScreenVolumePercent, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicScreenVolumePercent, 80);
    lv_obj_set_y(ui_MusicScreenVolumePercent, 21);
    lv_obj_set_align(ui_MusicScreenVolumePercent, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicScreenVolumePercent, "80%");
    lv_obj_set_style_text_color(ui_MusicScreenVolumePercent, lv_color_hex(0xEE1E1E), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicScreenVolumePercent, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicScreenVolumePercent, &lv_font_montserrat_20, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicScreenVolumePercent, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicScreenVolumePercent, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicTimePanel = lv_obj_create(ui_MusicScreen);
    lv_obj_set_width(ui_MusicTimePanel, 273);
    lv_obj_set_height(ui_MusicTimePanel, 32);
    lv_obj_set_x(ui_MusicTimePanel, -20);
    lv_obj_set_y(ui_MusicTimePanel, 49);
    lv_obj_set_align(ui_MusicTimePanel, LV_ALIGN_CENTER);
    lv_obj_remove_flag(ui_MusicTimePanel, LV_OBJ_FLAG_SCROLLABLE);      /// Flags
    lv_obj_set_style_bg_color(ui_MusicTimePanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicTimePanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_border_side(ui_MusicTimePanel, LV_BORDER_SIDE_NONE, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicCurrTimeMinPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicCurrTimeMinPanel, 35);
    lv_obj_set_height(ui_MusicCurrTimeMinPanel, 43);
    lv_obj_set_x(ui_MusicCurrTimeMinPanel, -68);
    lv_obj_set_y(ui_MusicCurrTimeMinPanel, 3);
    lv_obj_set_align(ui_MusicCurrTimeMinPanel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicCurrTimeMinPanel, "01");
    lv_obj_set_style_text_color(ui_MusicCurrTimeMinPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicCurrTimeMinPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicCurrTimeMinPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicCurrTimeMinPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicCurrTimeMinPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicCurrTimeDotsPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicCurrTimeDotsPanel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicCurrTimeDotsPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicCurrTimeDotsPanel, -47);
    lv_obj_set_y(ui_MusicCurrTimeDotsPanel, -3);
    lv_obj_set_align(ui_MusicCurrTimeDotsPanel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicCurrTimeDotsPanel, ":");
    lv_obj_set_style_text_color(ui_MusicCurrTimeDotsPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicCurrTimeDotsPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicCurrTimeDotsPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicCurrTimeDotsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicCurrTimeDotsPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicCurrTimeSecPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicCurrTimeSecPanel, 43);
    lv_obj_set_height(ui_MusicCurrTimeSecPanel, 43);
    lv_obj_set_x(ui_MusicCurrTimeSecPanel, -16);
    lv_obj_set_y(ui_MusicCurrTimeSecPanel, 3);
    lv_obj_set_align(ui_MusicCurrTimeSecPanel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicCurrTimeSecPanel, "45");
    lv_obj_set_style_text_color(ui_MusicCurrTimeSecPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicCurrTimeSecPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicCurrTimeSecPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicCurrTimeSecPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicCurrTimeSecPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicTimeSlashPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicTimeSlashPanel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicTimeSlashPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicTimeSlashPanel, 19);
    lv_obj_set_y(ui_MusicTimeSlashPanel, 0);
    lv_obj_set_align(ui_MusicTimeSlashPanel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTimeSlashPanel, "/");
    lv_obj_set_style_text_color(ui_MusicTimeSlashPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicTimeSlashPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicTimeSlashPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicTimeSlashPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicTimeSlashPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicTotalTimeMinPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicTotalTimeMinPanel, 40);
    lv_obj_set_height(ui_MusicTotalTimeMinPanel, 43);
    lv_obj_set_x(ui_MusicTotalTimeMinPanel, 52);
    lv_obj_set_y(ui_MusicTotalTimeMinPanel, 3);
    lv_obj_set_align(ui_MusicTotalTimeMinPanel, LV_ALIGN_CENTER);
    lv_label_set_long_mode(ui_MusicTotalTimeMinPanel, LV_LABEL_LONG_CLIP);
    lv_label_set_text(ui_MusicTotalTimeMinPanel, "03");
    lv_obj_set_style_text_color(ui_MusicTotalTimeMinPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicTotalTimeMinPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicTotalTimeMinPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicTotalTimeMinPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicTotalTimeMinPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicTotalTimeDotsPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicTotalTimeDotsPanel, LV_SIZE_CONTENT);   /// 1
    lv_obj_set_height(ui_MusicTotalTimeDotsPanel, LV_SIZE_CONTENT);    /// 1
    lv_obj_set_x(ui_MusicTotalTimeDotsPanel, 82);
    lv_obj_set_y(ui_MusicTotalTimeDotsPanel, -3);
    lv_obj_set_align(ui_MusicTotalTimeDotsPanel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTotalTimeDotsPanel, ":");
    lv_obj_set_style_text_color(ui_MusicTotalTimeDotsPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicTotalTimeDotsPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicTotalTimeDotsPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicTotalTimeDotsPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicTotalTimeDotsPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicTotalTimeSecPanel = lv_label_create(ui_MusicTimePanel);
    lv_obj_set_width(ui_MusicTotalTimeSecPanel, 43);
    lv_obj_set_height(ui_MusicTotalTimeSecPanel, 43);
    lv_obj_set_x(ui_MusicTotalTimeSecPanel, 111);
    lv_obj_set_y(ui_MusicTotalTimeSecPanel, 3);
    lv_obj_set_align(ui_MusicTotalTimeSecPanel, LV_ALIGN_CENTER);
    lv_label_set_text(ui_MusicTotalTimeSecPanel, "05");
    lv_obj_set_style_text_color(ui_MusicTotalTimeSecPanel, lv_color_hex(0x808080), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_text_opa(ui_MusicTotalTimeSecPanel, (lv_opa_t)255,(lv_style_selector_t) LV_PART_MAIN);
    lv_obj_set_style_text_font(ui_MusicTotalTimeSecPanel, &lv_font_montserrat_28, (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_color(ui_MusicTotalTimeSecPanel, lv_color_hex(0x000000), (lv_style_selector_t)LV_PART_MAIN);
    lv_obj_set_style_bg_opa(ui_MusicTotalTimeSecPanel, (lv_opa_t)0, (lv_style_selector_t)LV_PART_MAIN);

    ui_MusicScreenHomeBtnPanel = ui_Button_create(ui_MusicScreen);
    lv_obj_set_x(ui_MusicScreenHomeBtnPanel, 148);
    lv_obj_set_y(ui_MusicScreenHomeBtnPanel, 123);

    lv_image_set_src(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNICON), &ui_img_house_png);
    lv_obj_set_x(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNICON), -1);
    lv_obj_set_y(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNICON), -14);

    lv_image_set_src(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNBAR), &ui_img_btn_bg_3_png);
    lv_obj_set_x(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNBAR), 13);
    lv_obj_set_y(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNBAR), 2);
    lv_image_set_rotation(ui_comp_get_child(ui_MusicScreenHomeBtnPanel, UI_COMP_BUTTON_BTNBAR), 80);

    lv_obj_add_event_cb(ui_MusicScreenVolumeArc, ui_event_MusicScreenVolumeArc, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MusicScreenHomeBtnPanel, ui_event_MusicScreenHomeBtnPanel_Button, (lv_event_code_t)LV_EVENT_ALL, NULL);
    lv_obj_add_event_cb(ui_MusicScreen, ui_event_MusicScreen, (lv_event_code_t)LV_EVENT_ALL, NULL);

}

void ui_MusicScreen_screen_destroy(void)
{
    if(ui_MusicScreen) lv_obj_del(ui_MusicScreen);

    // NULL screen variables
    ui_MusicScreen = NULL;
    ui_MusicTitleLabel = NULL;
    ui_MusicPrevButtonPanel = NULL;
    ui_MusicPausePlayButtonPanel = NULL;
    ui_MusicNextButtonPanel = NULL;
    ui_MusicScreenVolumePanel = NULL;
    ui_MusicScreenVolumeArc = NULL;
    ui_MusicScreenVolumeNameLabel = NULL;
    ui_MusicScreenVolumePercent = NULL;
    ui_MusicTimePanel = NULL;
    ui_MusicCurrTimeMinPanel = NULL;
    ui_MusicCurrTimeDotsPanel = NULL;
    ui_MusicCurrTimeSecPanel = NULL;
    ui_MusicTimeSlashPanel = NULL;
    ui_MusicTotalTimeMinPanel = NULL;
    ui_MusicTotalTimeDotsPanel = NULL;
    ui_MusicTotalTimeSecPanel = NULL;
    ui_MusicScreenHomeBtnPanel = NULL;

}
