// This file was generated by SquareLine Studio
// SquareLine Studio version: SquareLine Studio 1.5.3
// LVGL version: 9.2.2
// Project name: SquareLine_Project

#ifndef UI_WEATHERSCREEN1_H
#define UI_WEATHERSCREEN1_H

#ifdef __cplusplus
extern "C" {
#endif

// SCREEN: ui_WeatherScreen1
extern void ui_WeatherScreen1_screen_init(void);
extern void ui_WeatherScreen1_screen_destroy(void);
extern void ui_event_WeatherScreen1(lv_event_t * e);
extern lv_obj_t * ui_WeatherScreen1;
extern lv_obj_t * ui_WeatherScreen1CityNamePanel;
extern lv_obj_t * ui_weather1CityLabel;
extern lv_obj_t * ui_weather1DateLabel;
extern lv_obj_t * ui_WeatherScreen1TemprtrLabel;
extern lv_obj_t * ui_WeatherScreen1DataPanel;
extern lv_obj_t * ui_weather1DescriptionLabel1;
extern lv_obj_t * ui_weather1DataLabel1;
extern lv_obj_t * ui_WeatherScreen1RainPanel;
extern lv_obj_t * ui_RainImg;
extern lv_obj_t * ui_RainPercentLabel;
extern lv_obj_t * ui_WeatherScreen1WindPanel;
extern lv_obj_t * ui_RainImg1;
extern lv_obj_t * ui_WindSpeedLabel;
extern lv_obj_t * ui_WeatherScreen1SliderPanel;
extern lv_obj_t * ui_SliderDot1Panel;
extern lv_obj_t * ui_SliderDot1Panel1;
extern lv_obj_t * ui_SunImg;
extern lv_obj_t * ui_CloudsImg;
extern void ui_event_WeatherScrn1HomeBtn_Button(lv_event_t * e);
extern lv_obj_t * ui_WeatherScrn1HomeBtn;
extern lv_obj_t * ui_WeatherScreen1WindAnimImg;
// CUSTOM VARIABLES

#ifdef __cplusplus
} /*extern "C"*/
#endif

#endif

