/* Generated by bento-release.sh package — do not edit.
 *
 * Symbols this archive exports that no shipped header declares.
 * Each prototype is copied verbatim from the caller in the BENTO
 * tree that already declares it, so the signature is the one the
 * firmware really links against, not a guess.
 */
#pragma once

/* cm55_controls_snapshot — WEAK. Define your own; yours wins at link time. */
/* game_sprite_create — WEAK. Define your own; yours wins at link time. */
/* game_sprite_lookup — WEAK. Define your own; yours wins at link time. */
/* game_sprite_set — WEAK. Define your own; yours wins at link time. */
/* ipc_ui_ext_clear_all — WEAK. Define your own; yours wins at link time. */
/* ipc_ui_platform_diag — WEAK. Define your own; yours wins at link time. */

/* declarations recovered: 0 */
