/* Generated by bento-release.sh package — do not edit.
 *
 * Symbols this archive exports that no shipped header declares.
 * Each prototype is copied verbatim from the caller in the BENTO
 * tree that already declares it, so the signature is the one the
 * firmware really links against, not a guess.
 */
#pragma once

/* NUS_UUID_CHAR_RX — exported, but no declaration found in the tree */
/* NUS_UUID_CHAR_TX — exported, but no declaration found in the tree */
/* NUS_UUID_SERVICE — exported, but no declaration found in the tree */
/* app_wifi_connect_direct — WEAK. Define your own; yours wins at link time. */
/* app_wifi_disconnect — WEAK. Define your own; yours wins at link time. */
/* app_wifi_get_ipv4 — WEAK. Define your own; yours wins at link time. */
extern int ipc_bento_buddy_rx_init(void);
/* ipc_bento_buddy_send — exported, but no declaration found in the tree */
/* lfs_load_wifi_creds — WEAK. Define your own; yours wins at link time. */
/* lfs_save_wifi_creds — WEAK. Define your own; yours wins at link time. */
extern int nus_fp_device_write_bytes(const uint8_t *b, size_t n);
/* nus_gatt_database — exported, but no declaration found in the tree */
/* nus_gatt_database_len — exported, but no declaration found in the tree */
extern int nus_protocol_get_link_encrypted(void);

/* declarations recovered: 3 */
