/*******************************************************************************
 * File Name: cycfg_connectivity_bt.h
 *
 * Description: Minimal stub of the Bluetooth Configurator output expected by
 *              cybsp_bt_config.c. Defines low-power mode flag and version
 *              macros that the BSP glue includes at build time.
 *
 *              In a full ModusToolbox flow this file is generated by the
 *              Bluetooth Configurator GUI from a .cybt design. Since we
 *              describe the NUS GATT DB manually in nus_gatt_db.{c,h}, this
 *              stub only needs to satisfy BSP compilation.
 *
 *              Scope: proj_cm33_ns build only, guarded by COMPONENT_WICED_BLE.
 *
 *******************************************************************************/

#ifndef CYCFG_CONNECTIVITY_BT_H
#define CYCFG_CONNECTIVITY_BT_H

#ifdef __cplusplus
extern "C" {
#endif

/* Low-power mode (HCI flow control sleep). CYW55500 supports LPM on the
 * BT_HOST_WAKE / BT_DEV_WAKE GPIO pair defined in the BSP pin config. */
#ifndef CYCFG_BT_LP_ENABLED
#define CYCFG_BT_LP_ENABLED              (1)
#endif

/* Platform config identifier reported by the BT stack in diagnostics.
 * Any non-zero value is accepted; this matches the Configurator default. */
#ifndef CYCFG_BT_CONFIGURATOR_VERSION
#define CYCFG_BT_CONFIGURATOR_VERSION    (1)
#endif

#ifdef __cplusplus
}
#endif

#endif /* CYCFG_CONNECTIVITY_BT_H */
