/* GENERATED by tools/gen_examples_table.py — DO NOT EDIT.
 *
 * Regenerate after adding or removing an example:
 *     tools/gen_examples_table.py
 * Verify it is current (CI / release gate):
 *     tools/gen_examples_table.py --check
 *
 * Each row is stated by the example file itself, in its own header block, so
 * this table cannot drift from what is on disk.
 */

#include "sdk_examples_cm33.h"

int example_sensors_i2c_bus_scan(void);
int example_sensors_read_imu(void);
int example_sensors_read_magnetometer(void);
int example_sensors_read_environment(void);
int example_sensors_auto_push_task(void);
int example_sensors_raw_register_access(void);
int example_io_read_buttons(void);
int example_io_capsense_slider(void);
int example_io_read_potentiometers(void);
int example_io_gpio_led_button(void);
#if BENTO_HAS_MPY
int example_mpy_secure_link_registry(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_link_ipc(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_https_session(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_circuit_breaker(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_rate_limit(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_session_memory(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_trust_policy(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_tacp(void);
#endif
int example_net_wifi_join(void);
#if BENTO_HAS_MPY
int example_mpy_secure_reference(void);
#endif
#if BENTO_HAS_MPY
int example_mpy_secure_model_signature_hook(void);
#endif
int example_tesaiot_hsm_chip_ownership(void);
int example_tesaiot_hsm_touch_hold(void);
int example_tesaiot_hsm_csr_enrolment(void);
int example_tesaiot_hsm_protected_update(void);
int example_tesaiot_hsm_reference(void);
#if BENTO_HAS_MPY
int example_mpy_secure_wifi_creds(void);
#endif
int example_storage_littlefs_basics(void);
#if ENABLE_PAGE_BENTO_BUDDY
int example_ble_bring_up_and_talk(void);
#endif
#if ENABLE_PAGE_BENTO_BUDDY
int example_ble_host_protocol(void);
#endif
#if ENABLE_PAGE_BENTO_BUDDY
int example_ble_reference(void);
#endif

const sdk33_example_t g_sdk_examples_cm33[] = {
    { "cm33/sensors/01_i2c_bus_scan", "Scan the sensor I2C bus",
      "the bus has one mutex and several owners - take it, scan, give it back, and quiesce the auto task first so you are not fighting it",
      "sensor_i2c_is_init, sensor_i2c_lock, sensor_i2c_scan, sensor_i2c_unlock, sensor_auto_is_running, sensor_auto_stop, sensor_auto_start",
      SDK33_GRP_SENSORS, example_sensors_i2c_bus_scan },
    { "cm33/sensors/02_read_imu", "Read the BMI270 accelerometer and gyroscope",
      "prove the wire before you trust the driver, the real init order, and one lock per SAMPLE rather than one per register",
      "bmi270_read_chip_id, bmi270_read_accel, bmi270_read_gyro, bmi270_read_temperature, sensor_i2c_lock, sensor_i2c_unlock, sensor_auto_is_running",
      SDK33_GRP_SENSORS, example_sensors_read_imu },
    { "cm33/sensors/03_read_magnetometer", "Read the BMM350 magnetometer and calibrate the compass",
      "a compass is useless until hard-iron calibration converges - how to drive that, how to know when it has, and why heading_from_xy beats a second bus read",
      "bmm350_read_chip_id, bmm350_read_xyz, bmm350_read_heading, bmm350_cal_update, bmm350_cal_get_offsets, bmm350_heading_from_xy, bmm350_cal_reset, sensor_i2c_lock, sensor_i2c_unlock, bmm350_reinit, bmm350_diagnose, bmm350_debug_read",
      SDK33_GRP_SENSORS, example_sensors_read_magnetometer },
    { "cm33/sensors/04_read_environment", "Read pressure, air temperature and humidity (AI Kit)",
      "read_both() is not a convenience wrapper - it halves the bus traffic; and the two parts report two different temperatures",
      "dps368_read_product_id, dps368_read_both, dps368_read_pressure, dps368_read_temperature, sht40_read_serial, sht40_read_both, sht40_read_temperature, sht40_read_humidity, sensor_i2c_lock, sensor_i2c_unlock",
      SDK33_GRP_SENSORS, example_sensors_read_environment },
    { "cm33/sensors/05_auto_push_task", "Drive the background sensor-push task",
      "retune the publisher that feeds the display and MicroPython - mask, rate, the 50 ms cliff, the free cache - and put it back",
      "sensor_auto_is_running, sensor_auto_get_mask, sensor_auto_set_mask, sensor_auto_enable, sensor_auto_disable, sensor_auto_get_rate, sensor_auto_set_rate, sensor_auto_get_push_count, sensor_auto_stop, sensor_auto_start, sensor_auto_get_bmi270",
      SDK33_GRP_SENSORS, example_sensors_auto_push_task },
    { "cm33/sensors/06_raw_register_access", "Talk to any device on the sensor bus directly",
      "the escape hatch - register reads, a safe read-modify-write, and the command-response form for parts that have no registers at all",
      "sensor_i2c_read_byte, sensor_i2c_write_byte, sensor_i2c_read_reg, sensor_i2c_write_reg, sensor_i2c_write_raw, sensor_i2c_read_raw, sensor_i2c_is_init, sensor_i2c_lock, sensor_i2c_unlock",
      SDK33_GRP_SENSORS, example_sensors_raw_register_access },
    { "cm33/io/01_read_buttons", "Read the CapSense buttons",
      "capture the idle baseline with fingers OFF the pad, poll the two buttons, and know which of the two CapSense backends your build linked — they read two different I2C buses",
      "capsense_init, capsense_read",
      SDK33_GRP_IO, example_io_read_buttons },
    { "cm33/io/02_capsense_slider", "Read the CapSense slider position",
      "the slider is 0..100 with no \"not touched\" value, so you need a release test and a hysteresis band before you drive anything with it",
      "capsense_init, capsense_read_slider",
      SDK33_GRP_IO, example_io_capsense_slider },
    { "cm33/io/03_read_potentiometers", "Read the potentiometer three ways",
      "raw counts, percent and volts off one SAR channel — and which channel that actually is, which is not the one most people assume",
      "potentiometer_init, potentiometer_read_raw, potentiometer_read_percent, potentiometer_read_voltage",
      SDK33_GRP_IO, example_io_read_potentiometers },
    { "cm33/io/04_gpio_led_button", "Drive the board LEDs and read the user button",
      "the PDL calls behind gpio.led()/gpio.button(), the drive modes that make them work, and how to debounce a button without blocking",
      "Cy_GPIO_Pin_FastInit, Cy_GPIO_Set, Cy_GPIO_Clr, Cy_GPIO_Inv, Cy_GPIO_Write, Cy_GPIO_Read, CYBSP_USER_LED1_PORT, CYBSP_USER_BTN1_PORT",
      SDK33_GRP_IO, example_io_gpio_led_button },
#if BENTO_HAS_MPY
    { "cm33/connectivity/01_link_registry", "Register and look up a transport link",
      "how a backend joins the bento_link registry, and why registration is one-way — look up before you register, never register twice",
      "bento_link_register, bento_link_get, bento_link_at",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_link_registry },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/02_link_ipc_backend", "Bring up the IPC backend and pull data back from CM55",
      "the bidirectional QUERY — send a request, wait for CM55 to fill a shared-memory response, and why that response must be SHAREDMEM",
      "bento_link_ipc_init, bento_link_ipc_query, bento_link_get",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_link_ipc },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/03_https_session", "One HTTPS session, end to end",
      "connect, GET, POST, disconnect against the TESAIoT gateway — and when the plaintext door is the right one and when it is a mistake",
      "claw_https_connect, claw_https_connected, claw_https_get, claw_https_post, claw_https_disconnect, claw_http_connect_insecure",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_https_session },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/04_circuit_breaker", "Stop hammering a backend that is already failing",
      "drive the breaker CLOSED -> OPEN -> HALFOPEN -> CLOSED and read the cooldown, so a dead backend costs three attempts, not thousands",
      "claw_cb_init, claw_cb_allow, claw_cb_failure, claw_cb_success, claw_cb_state, claw_cb_cooldown_remaining",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_circuit_breaker },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/05_rate_limit", "Cap how often one tool may be called",
      "check-then-record around every tool call, per-tool budgets, and the two ways the limiter lets calls through that you must design for",
      "claw_rate_init, claw_rate_set, claw_rate_check, claw_rate_record",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_rate_limit },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/06_session_memory", "Keep a conversation, and remember facts across it",
      "the RAM ring vs the persistent key-value store, how to build an LLM context out of both, and the one call that must run on the MPY task",
      "claw_session_init, claw_session_add, claw_session_count, claw_session_dirty, claw_session_clear, claw_session_build_context, claw_session_flush, claw_memory_set, claw_memory_get",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_session_memory },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/07_trust_policy", "Let the transport decide which tools may run",
      "set the trust level when a session opens, gate every tool on its own risk class, and put the level back when the session closes",
      "claw_trust_set, claw_trust_get, claw_trust_allows",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_trust_policy },
#endif
#if BENTO_HAS_MPY
    { "cm33/connectivity/08_tacp_host_protocol", "Pump the TACP host link and answer the IDE",
      "the one-owner rule for the UART, the poll/drain loop, framed responses, and what \"_from_isr\" buys you and what it costs",
      "tacp_init, tacp_poll_uart, tacp_ring_buf_readable, tacp_ring_buf_read, tacp_claw_respond, tacp_request_delete_main_from_isr",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_tacp },
#endif
    { "cm33/connectivity/10_wifi_join", "Join a Wi-Fi network",
      "the whole join on CM33_NS — bring the radio up, take credentials from a store instead of a #define, connect, read the IP and the associated AP back, and put the link down again",
      "app_wifi_is_ready, app_wifi_init, app_wifi_connect_direct, app_wifi_get_ipv4, app_wifi_disconnect, cy_wcm_is_connected_to_ap, cy_wcm_get_ip_addr, cy_wcm_get_associated_ap_info, lfs_load_wifi_creds, tesaiot_config_get",
      SDK33_GRP_CONNECTIVITY, example_net_wifi_join },
#if BENTO_HAS_MPY
    { "cm33/connectivity/ref_claw", "Reference list — every read-only call, and the two module objects",
      "which mpy_secure calls are safe to make from any task at any time, and how the MicroPython module objects are referenced",
      "claw_https_connected, claw_cb_state, claw_cb_cooldown_remaining, claw_trust_get, claw_rate_check, claw_session_count, claw_session_dirty, claw_session_build_context, claw_memory_get, lfs_wifi_creds_ready, lfs_wifi_creds_needs_resave, tacp_ring_buf_readable, bento_link_at, bento_link_get, mp_module_edge_ai, mp_module_optiga",
      SDK33_GRP_CONNECTIVITY, example_mpy_secure_reference },
#endif
#if BENTO_HAS_MPY
    { "cm33/security/02_model_signature_hook", "Replace the staged-model signature check with your own",
      "how to override a WEAK symbol the archive exports, and how to return a verdict that does not pretend to know more than it does",
      "optiga_verify_staged_model",
      SDK33_GRP_SECURITY, example_mpy_secure_model_signature_hook },
#endif
    { "cm33/security/03_chip_ownership", "Take the secure element, use it, give it back",
      "the init-before-anything rule, the three names for one re-entrant gate, and why optiga_chip_enter() is not an \"is the chip up?\" test",
      "optiga_manager_init, optiga_manager_lock, optiga_manager_unlock, optiga_manager_acquire, optiga_manager_release, optiga_chip_enter, optiga_chip_exit",
      SDK33_GRP_SECURITY, example_tesaiot_hsm_chip_ownership },
    { "cm33/security/04_touch_hold", "Keep the touch controller off the bus while the chip works",
      "the counted hold/release pair, why it must wrap the WHOLE operation and not just its setup, and what the user sees while it is held",
      "optiga_manager_touch_hold, optiga_manager_touch_hold_reason, optiga_manager_touch_release",
      SDK33_GRP_SECURITY, example_tesaiot_hsm_touch_hold },
    { "cm33/security/05_csr_enrolment", "Publish a CSR and track the request that follows it",
      "the request bookkeeping — correlation id, target and anchor OIDs — and the buffer contract publish_csr() imposes on its caller",
      "publish_csr, trustm_update_state, trustm_reset_state, trustm_current_correlation_id, trustm_requested_target_oid, trustm_requested_anchor_oid",
      SDK33_GRP_SECURITY, example_tesaiot_hsm_csr_enrolment },
    { "cm33/security/06_protected_update", "Ask the platform for a Protected Update — and what it changes",
      "the request, the anti-rollback counter, what a manifest lock does and undoes, and the one chip change that no reflash can undo",
      "tesaiot_publish_protected_update, tesaiot_run_protected_update_isolated_test",
      SDK33_GRP_SECURITY, example_tesaiot_hsm_protected_update },
    { "cm33/security/ref_hsm", "Reference list — read the HSM's state without starting anything",
      "which calls answer a question without a chip transaction, and the one probe that is balanced rather than free",
      "optiga_manager_lock, optiga_manager_unlock, trustm_requested_target_oid, trustm_requested_anchor_oid, trustm_current_correlation_id",
      SDK33_GRP_SECURITY, example_tesaiot_hsm_reference },
#if BENTO_HAS_MPY
    { "cm33/storage/03_wifi_creds_lfs", "Read and write saved WiFi networks on LittleFS",
      "the credential store's readiness contract, the checksum-migration flag, and why every call but two must run on the MicroPython task",
      "lfs_wifi_creds_ready, lfs_wifi_creds_needs_resave, lfs_wifi_creds_init, lfs_wifi_creds_read, lfs_wifi_creds_write, lfs_wifi_creds_deinit",
      SDK33_GRP_STORAGE, example_mpy_secure_wifi_creds },
#endif
    { "cm33/storage/10_littlefs_basics", "Mount LittleFS in C, write a file, read it back",
      "the geometry contract the two variants share, why the C mount only exists under mtb-only, and what the API deliberately does NOT give you — no directory read, no unmount, no remove",
      "bento_storage_init, bento_storage_ready, bento_storage_read_file, bento_storage_write_file, bento_storage_format",
      SDK33_GRP_STORAGE, example_storage_littlefs_basics },
#if ENABLE_PAGE_BENTO_BUDDY
    { "cm33/ble/01_nus_bring_up_and_talk", "Bring up NUS, pair, and exchange bytes (STARTS THE BLE RADIO)",
      "the whole transport in one pass — advertise, read the link state, feed the newline framer, send a frame, answer a permission prompt, and stop cleanly",
      "ble_nus_init, ble_nus_get_state, ble_nus_get_adv_name, ble_nus_send, ble_nus_rearm_advertising, ble_nus_deinit, ble_nus_passkey_cb, nus_gatt_database, nus_gatt_database_len, NUS_UUID_SERVICE, NUS_UUID_CHAR_RX, NUS_UUID_CHAR_TX, nus_protocol_init, nus_on_rx_bytes, nus_protocol_tick, nus_protocol_set_link_encrypted, nus_protocol_get_link_encrypted, nus_protocol_send_permission",
      SDK33_GRP_BLE, example_ble_bring_up_and_talk },
#endif
#if ENABLE_PAGE_BENTO_BUDDY
    { "cm33/ble/02_host_protocol", "Speak the Bento Buddy wire protocol end to end",
      "dispatch a command, emit its ack, queue the acks a human still owes, decode chunked base64, receive a pushed folder, and accumulate a streamed agent answer",
      "nus_commands_dispatch, nus_commands_emit_ack, nus_commands_handle_time_sync, nus_emit_event, nus_events_push_pending_ack, nus_events_drain_pending_ack, nus_events_pending_ack_count, nus_b64_init, nus_b64_feed, nus_b64_flush, nus_fp_char_begin, nus_fp_file, nus_fp_chunk, nus_fp_file_end, nus_fp_char_end, nus_fp_is_active, nus_fp_device_write_bytes, nus_agent_note_ask, nus_agent_handle_token, nus_agent_handle_tool_call, nus_agent_handle_done, nus_agent_buffer_len, nus_agent_reset",
      SDK33_GRP_BLE, example_ble_host_protocol },
#endif
#if ENABLE_PAGE_BENTO_BUDDY
    { "cm33/ble/ref_ble", "Reference list — everything else in the ble_nus module",
      "what each remaining call is for, when to reach for it, and what it gives back — devmode, firmware identity, OTA consent, the radio scheduler, sensor and voice streams, the CM55 bridge, and the five weak stubs you are expected to replace",
      "ble_nus_get_diagnostics, fw_hash_compute_at_boot, fw_hash_hex, fw_hash_prefix8, fw_hash_get_diagnostics, bento_fw_handle_query, bento_fw_handle_update_begin, bento_fw_on_user_decision, bento_fw_emit_boot_complete, bento_devmode_init, bento_devmode_secret_fp_hex, bento_devmode_secret_hex, bento_devmode_nonce_issue, bento_devmode_unlock, bento_devmode_is_unlocked, bento_devmode_lock, bento_devmode_emit_provision, radio_scheduler_init, radio_scheduler_get_mode, radio_scheduler_get_status, radio_scheduler_get_boot_mode, radio_scheduler_set_boot_mode, radio_scheduler_request_mode, radio_scheduler_set_on_state, radio_scheduler_set_wifi_creds, radio_mode_str, nus_radio_emit_state_event, sensor_stream_init, sensor_stream_start, sensor_stream_stop, sensor_stream_stop_all, sensor_stream_is_active, sensor_stream_dropped_count, voice_capture_start, voice_capture_stop, voice_capture_is_running, ipc_bento_buddy_rx_init, ipc_bento_buddy_send, bento_buddy_request_start, bento_buddy_request_stop, bento_buddy_auto_start_install, app_wifi_connect_direct, app_wifi_disconnect, app_wifi_get_ipv4, lfs_save_wifi_creds, lfs_load_wifi_creds",
      SDK33_GRP_BLE, example_ble_reference },
#endif
};

const unsigned g_sdk_example_cm33_count =
    (unsigned)(sizeof(g_sdk_examples_cm33) / sizeof(g_sdk_examples_cm33[0]));
