/* Generated by bento-release.sh package — do not edit.
 *
 * Symbols this archive exports that no shipped header declares.
 * Each prototype is copied verbatim from the caller in the BENTO
 * tree that already declares it, so the signature is the one the
 * firmware really links against, not a guess.
 */
#pragma once

/* calculate_idle_percentage — exported, but no declaration found in the tree */
/* disp_touch_i2c_controller_context — exported, but no declaration found in the tree */
/* g_tesaiot_display_diag — exported, but no declaration found in the tree */
/* rtos_cm55_gfx_task_handle — exported, but no declaration found in the tree */
/* tesaiot_display_ready — exported, but no declaration found in the tree */

/* declarations recovered: 0 */
