/* Generated by bento-release.sh package — do not edit.
 *
 * Symbols this archive exports that no shipped header declares.
 * Each prototype is copied verbatim from the caller in the BENTO
 * tree that already declares it, so the signature is the one the
 * firmware really links against, not a guess.
 */
#pragma once

extern bool bento_link_ipc_init(void);
/* bento_link_ipc_query — exported, but no declaration found in the tree */
/* mp_module_edge_ai — exported, but no declaration found in the tree */
/* mp_module_optiga — exported, but no declaration found in the tree */
/* optiga_verify_staged_model — WEAK. Define your own; yours wins at link time. */

/* declarations recovered: 1 */
