/* AUTO-GENERATED by gen_fw_id_config.py — DO NOT EDIT.
 * SKU  : TESAIOT-CLAW-AI-MPY-DEVKIT
 * UUID : 39db58bd-f159-522d-8d48-377512c21df3
 * board: KIT_PSE84_AI -> AI
 */
#ifndef FW_ID_CONFIG_H
#define FW_ID_CONFIG_H
#define FW_ID_SKU        "TESAIOT-CLAW-AI-MPY-DEVKIT"
#define FW_ID_VERSION    "1.9.0"
#define FW_ID_BOARD      "KIT_PSE84_AI"
#define FW_ID_FAMILY     "CLAW"
#define FW_ID_UUID_BYTES 0x39,0xdb,0x58,0xbd,0xf1,0x59,0x52,0x2d,0x8d,0x48,0x37,0x75,0x12,0xc2,0x1d,0xf3
#define FW_ID_RELEASE    0
#endif /* FW_ID_CONFIG_H */
