#!/usr/bin/env python3
"""gen_fw_id_config.py — emit the build-time fw_id_config.h for a project.

Derives BOARD from the build TARGET, composes + validates the SKU (contract §3), computes the
UUIDv5 (contract §4), and prints a C header defining FW_ID_* macros consumed by fw_identity.c.
Using a generated header (not -D string defines) avoids make/shell quote-escaping pitfalls and
is inspectable.

Usage:
    gen_fw_id_config.py --family CLAW --app GAME [--variant W4P3] \
        --version 1.3.2 --target KIT_PSE84_AI [--release 0|1]
"""
import argparse
import re
import sys
import uuid

TESAIOT_FW_NS = uuid.uuid5(uuid.NAMESPACE_DNS, "firmware-identity.tesaiot.io")

# TARGET -> BOARD short token used in the SKU (contract §3)
BOARD_MAP = {
    "KIT_PSE84_AI": "AI",
    "APP_KIT_PSE84_AI": "AI",
    "APP_KIT_PSE84_EVAL_EPC2": "EPC2",
    "KIT_PSE84_EVAL_EPC2": "EPC2",
}

# TARGET -> record `board` field (contract §2.2, must fit char board[16] incl. NUL, so <=15).
# NOTE (contract finding): the EPC2 kit name "KIT_PSE84_EVAL_EPC2" (19) does not fit board[16];
# a fitting token is used and flagged for the contract owners.
BOARD_FIELD_MAP = {
    "KIT_PSE84_AI": "KIT_PSE84_AI",
    "APP_KIT_PSE84_AI": "KIT_PSE84_AI",
    "APP_KIT_PSE84_EVAL_EPC2": "KIT_EVAL_EPC2",
    "KIT_PSE84_EVAL_EPC2": "KIT_EVAL_EPC2",
}

_SEG = re.compile(r"^[A-Z0-9]+$")


def derive_board(target):
    if target in BOARD_MAP:
        return BOARD_MAP[target]
    # tolerant fallback: match on substring
    if "EVAL_EPC2" in target or "EPC2" in target:
        return "EPC2"
    if "AI" in target:
        return "AI"
    raise ValueError(f"cannot derive BOARD from TARGET={target!r}")


def compose_sku(family, board, app, variant):
    parts = ["TESAIOT", family, board, app]
    if variant:
        parts.append(variant)
    sku = "-".join(parts)
    # validate (contract §3)
    for seg in (family, board, app) + ((variant,) if variant else ()):
        if not _SEG.match(seg):
            raise ValueError(f"SKU segment {seg!r} must be uppercase [A-Z0-9]+")
    if len(sku) > 31:
        raise ValueError(f"SKU too long ({len(sku)}>31): {sku}")
    return sku


def main(argv):
    ap = argparse.ArgumentParser()
    ap.add_argument("--family", required=True)
    ap.add_argument("--app", required=True)
    ap.add_argument("--variant", default="")
    ap.add_argument("--version", required=True)
    ap.add_argument("--target", required=True)
    ap.add_argument("--release", default="0")
    a = ap.parse_args(argv[1:])

    fam = a.family.strip().upper()
    app = a.app.strip().upper()
    var = a.variant.strip().upper()
    ver = a.version.strip()
    if not re.match(r"^\d+\.\d+\.\d+$", ver):
        sys.stderr.write(f"FATAL: version {ver!r} is not MAJOR.MINOR.PATCH\n")
        return 2
    if len(ver) > 15:
        sys.stderr.write(f"FATAL: version {ver!r} exceeds 15 chars\n")
        return 2

    board = derive_board(a.target.strip())
    sku = compose_sku(fam, board, app, var)
    u = uuid.uuid5(TESAIOT_FW_NS, sku)
    uuid_bytes = ",".join(f"0x{b:02x}" for b in u.bytes)
    release = "1" if a.release.strip() in ("1", "true", "TRUE", "yes") else "0"

    print(f"""/* AUTO-GENERATED by gen_fw_id_config.py — DO NOT EDIT.
 * SKU  : {sku}
 * UUID : {u}
 * board: {a.target} -> {board}
 */
#ifndef FW_ID_CONFIG_H
#define FW_ID_CONFIG_H
#define FW_ID_SKU        "{sku}"
#define FW_ID_VERSION    "{ver}"
#define FW_ID_BOARD      "{board_token(a.target)}"
#define FW_ID_FAMILY     "{fam}"
#define FW_ID_UUID_BYTES {uuid_bytes}
#define FW_ID_RELEASE    {release}
#endif /* FW_ID_CONFIG_H */""")
    return 0


def board_token(target):
    """The record `board` field (contract §2.2). Must fit char board[16] (<=15 chars + NUL)."""
    t = target.strip()
    tok = BOARD_FIELD_MAP.get(t)
    if tok is None:
        tok = t[4:] if t.startswith("APP_") else t   # tolerant fallback
    if len(tok) > 15:
        raise ValueError(f"board field {tok!r} ({len(tok)}) exceeds 15 chars for board[16]")
    return tok


if __name__ == "__main__":
    sys.exit(main(sys.argv))
