/*******************************************************************************
 * File Name: character_lottie.c
 *
 * Description: See character_lottie.h. Renders the built-in default
 *              TESAIoT BENTO pack — the seven-state Lottie animations
 *              generated by characters/tesaiot-bento/gen_lotties.py and
 *              compiled into character_lottie_default.c via xxd. The
 *              default pack guarantees a visible animation even before
 *              the first folder push from Bento Desktop Buddy.
 *
 *              User-supplied packs pushed via the NUS folder-push state
 *              machine land in LittleFS at /buddy/<name>/ on the
 *              CM33_NS side. A future IPC bridge will let CM55 swap the
 *              baked-in pack for the pushed one — character_lottie_set_pack
 *              is the seam.
 *
 *              LVGL LV_USE_LOTTIE is already enabled in lv_conf.h, so the
 *              thorvg renderer handles playback directly.
 *
 ******************************************************************************/

#include "character_lottie.h"

#include <stddef.h>
#include <stdint.h>
#include <string.h>

/* Default pack arrays (auto-generated — see characters/tesaiot-bento/). */
extern const uint8_t default_sleep_json[];     extern const size_t default_sleep_json_len;
extern const uint8_t default_idle_json[];      extern const size_t default_idle_json_len;
extern const uint8_t default_busy_json[];      extern const size_t default_busy_json_len;
extern const uint8_t default_attention_json[]; extern const size_t default_attention_json_len;
extern const uint8_t default_celebrate_json[]; extern const size_t default_celebrate_json_len;
extern const uint8_t default_dizzy_json[];     extern const size_t default_dizzy_json_len;
extern const uint8_t default_heart_json[];     extern const size_t default_heart_json_len;

static lv_obj_t *s_lottie_widget = NULL;
static int       s_cur_state     = -1;

typedef struct {
    const uint8_t *bytes;
    const size_t  *len;
} state_src_t;

static const state_src_t s_pack[] = {
    [BENTO_BUDDY_STATE_SLEEP]     = { default_sleep_json,     &default_sleep_json_len },
    [BENTO_BUDDY_STATE_IDLE]      = { default_idle_json,      &default_idle_json_len },
    [BENTO_BUDDY_STATE_BUSY]      = { default_busy_json,      &default_busy_json_len },
    [BENTO_BUDDY_STATE_ATTENTION] = { default_attention_json, &default_attention_json_len },
    [BENTO_BUDDY_STATE_CELEBRATE] = { default_celebrate_json, &default_celebrate_json_len },
    [BENTO_BUDDY_STATE_DIZZY]     = { default_dizzy_json,     &default_dizzy_json_len },
    [BENTO_BUDDY_STATE_HEART]     = { default_heart_json,     &default_heart_json_len },
};

lv_obj_t *character_lottie_create(lv_obj_t *parent)
{
#if LV_USE_LOTTIE
    if (parent == NULL) return NULL;
    s_lottie_widget = lv_lottie_create(parent);
    if (s_lottie_widget == NULL) return NULL;
    lv_obj_set_size(s_lottie_widget, 200, 200);
    s_cur_state = -1;
    character_lottie_set_state(BENTO_BUDDY_STATE_IDLE);
    return s_lottie_widget;
#else
    (void)parent;
    return NULL;
#endif
}

void character_lottie_set_pack(const char *pack_name)
{
    (void)pack_name;
    /* Only the baked-in default pack is active in this revision. The
     * CM33_NS → CM55 IPC bridge that streams user-pushed packs from
     * LittleFS into this widget is tracked as a follow-up change. */
}

void character_lottie_set_state(bento_buddy_state_t state)
{
#if LV_USE_LOTTIE
    if (s_lottie_widget == NULL) return;
    if ((int)state == s_cur_state) return;
    size_t idx = (size_t)state;
    size_t count = sizeof(s_pack) / sizeof(s_pack[0]);
    if (idx >= count || s_pack[idx].bytes == NULL) return;
    lv_lottie_set_src_data(s_lottie_widget,
                           s_pack[idx].bytes,
                           *s_pack[idx].len);
    s_cur_state = (int)state;
#else
    (void)state;
#endif
}

void character_lottie_destroy(void)
{
    if (s_lottie_widget) {
        lv_obj_del(s_lottie_widget);
        s_lottie_widget = NULL;
    }
    s_cur_state = -1;
}

/*******************************************************************************
 * Minimal stub for bento.character.set.
 *
 * The production path is: nus_commands.c fires IPC_CMD_BUDDY_CHARACTER_SET
 * which page_bento_buddy.c receives and maps to the bento_buddy_state_t
 * enum, then calls character_lottie_set_state directly. This helper exists
 * so higher-level callers (MicroPython bindings, Red Team test harnesses)
 * have a name-indexed entry point without re-implementing the enum mapping.
 *
 * TODO: the `duration_ms` argument is currently recorded by the LCD page's
 * render loop but not enforced here. When the real Lottie engine exposes
 * per-animation playback length, use it to revert to the prior state
 * automatically once the animation ends, instead of wall-clock.
 ******************************************************************************/
int character_lottie_play(const char *name, uint32_t duration_ms)
{
    (void)duration_ms;
    if (name == NULL) return -1;

    bento_buddy_state_t target;
    if      (strcmp(name, "sleep")     == 0) target = BENTO_BUDDY_STATE_SLEEP;
    else if (strcmp(name, "idle")      == 0) target = BENTO_BUDDY_STATE_IDLE;
    else if (strcmp(name, "busy")      == 0) target = BENTO_BUDDY_STATE_BUSY;
    else if (strcmp(name, "attention") == 0) target = BENTO_BUDDY_STATE_ATTENTION;
    else if (strcmp(name, "wave")      == 0) target = BENTO_BUDDY_STATE_ATTENTION;
    else if (strcmp(name, "celebrate") == 0) target = BENTO_BUDDY_STATE_CELEBRATE;
    else if (strcmp(name, "dizzy")     == 0) target = BENTO_BUDDY_STATE_DIZZY;
    else if (strcmp(name, "heart")     == 0) target = BENTO_BUDDY_STATE_HEART;
    else                                     return -1;

    character_lottie_set_state(target);
    return 0;
}
