/* AUTO-GENERATED by gen_fw_id_config.py — DO NOT EDIT.
 * SKU  : TESAIOT-CLAW-AI-MTB-DEVKIT
 * UUID : 334a0945-046a-5cde-8d0c-af5340af63c2
 * board: KIT_PSE84_AI -> AI
 */
#ifndef FW_ID_CONFIG_H
#define FW_ID_CONFIG_H
#define FW_ID_SKU        "TESAIOT-CLAW-AI-MTB-DEVKIT"
#define FW_ID_VERSION    "1.9.0"
#define FW_ID_BOARD      "KIT_PSE84_AI"
#define FW_ID_FAMILY     "CLAW"
#define FW_ID_UUID_BYTES 0x33,0x4a,0x09,0x45,0x04,0x6a,0x5c,0xde,0x8d,0x0c,0xaf,0x53,0x40,0xaf,0x63,0xc2
#define FW_ID_RELEASE    0
#endif /* FW_ID_CONFIG_H */
